### ISSUE TITLE
Schreibzugriff auf E3DC

### ISSUE THREAD

**Issue by rellla** [nischram/E3dcGui#27]
Habe die Software auf einem BananaPi kompiliert und wollte fragen, ob man mit rscp grundsätzlich schreibend auf den Speicher zugreifen kann um z.B. die Ladesperre zu setzen?
Falls ja, war das im Original Beispielprogramm enthalten bzw. gibt es das Original Programm noch irgendwo als Download? Im Webportal taucht da nichts mehr auf...
Danke

**Comment by nischram** [comment]
Hallo,

ich habe in meine Applikation keine Möglichkeiten Einstellungen im E3DC zu verändern. Auch ist in der Beispielsapplikation nichts für diese Funktion. Es gibt nur einen Teil wie Daten gesendet werden und zwar wird die Authentifikation zum E3DC gesendet. Eigentlich ist jede Anfrage um Werte als Antwort zu erhalten, das gleiche um eine Einstellung zu senden. Aber leider habe ich mich trotzdem noch nicht mit dem senden von Einstellungen beschäftigt und kann da im Moment nicht weiterhelfen.
Aktuell habe ich die Datei im Download auch nicht gefunden, deswegen habe ich dir das Original mal in meinem Github hochgeladen. Ordner: _Rscp_ Datei: _RscpExample.zip_
In der Excel-Datei sind die TAGs zu finden und eventuell findest du etwas für die Ladesperre. 
Im Bereich "EMS" habe ich auf die schnelle die Sperrzeiten (IDLE_PERIODS) gefunden, eventuell benötigst du dies.

Viele Grüße Nico

**Comment by rellla** [comment]
Ok. Danke für die Datei, schau ich mir mal an... vielleicht finde ich was. Bis dahin kann man hier wieder schließen... Gruß rellla

**Comment by rellla** [comment]
Da ich nicht weiß, wie das mit Veröffentlichung der Dokumente ist, wäre es vielleicht besser, die Dinge zu verlinken. Sie sind hier zu finden: s10.e3dc.com/dokumentation/RscpExample.zip
Gruß rellla

**Comment by nischram** [comment]
Guter Einwand! Danke!
Ich werde schnellstens die Datei wieder löschen und den Link in die Anleitung aufnehmen. Bis dahin lasse ich diesen Issue offen.

Gruß Nico

**Comment by rellla** [comment]
Habe bei E3DC angefragt, wie die Lizenzbedingungen für den Code und Dokumentation sind und ob es veröffentlicht werden darf ...

**Comment by rellla** [comment]
Von E3DC habe ich die Anwort bekommen, dass die Software as-is mit Haftungsausschluss seitens E3DC für verursachte Schäden veröffentlicht werden darf und der Code nicht urheberrechtlich nicht als eigenes Werk deklariert werden darf. Ich warte noch auf Rückantwort, ob auch die Dokumentation veröffentlicht werden darf und wie es mit Veröffentlichung von eigenen Anpassungen aussieht.
Die Original Beispielsoftware habe ich in mein git geladen -> https://github.com/rellla/E3DC-Rscp

**Comment by nischram** [comment]
Super! Danke für deine Bemühung. Ich hatte es mir so schon fast gedacht.
Ich werde dann den Link nach E3DC und dein Link zur Applikation in meine Anleitung aufnehmen.
Danke Gruß Nico

**Comment by rellla** [comment]
Die Dokumentation wurde wieder ins Kundenportal hochgeladen. In den Dokumenten findet sich auch der Link zum Quellcode. 
Lt. E3DC darf die Software genutzt, modifiziert und verbreitet werden. Der Original-Quellcode liegt in meinem Repo. Dort habe ich auch eine erste modifierte Version hochgeladen, die ohne Abfrage-Schleifen funktioniert und auch ein Beispiel zum Setzen der Ladesperren enthält.
Gruß rellla

**Comment by nischram** [comment]
Ich habe so eben mit Version V1.70 die Links überarbeitet. Auch ein Link zu deine Github-Repo habe ich mit aufgenommen.
Danke für deine Mithilfe.
Gruß Nico
