### ISSUE TITLE
for loop not initialized in RscpMain.cpp

### ISSUE THREAD

**Issue by RalfJL** [nischram/E3dcGui#3]
Hi, 

I found a problem in RscpMain.cpp.
One "for loop" is not initialized correctly causing the program to not retrieve any value - sometimes.
The problem is taken over from the demo code from E3DC.

Line 436
for(unsigned int i; i < frame.data.size(); i++) {

Must be:
for(unsigned int i = 0; i < frame.data.size(); i++) {

First compilation with original code worked, but a little change in the source code caused all other runs to be stuck in the Authentication loop. 
Fixing the initialisation worked reliably.

I will report that to E3DC as well.

Thanks

Ralf

**Comment by nischram** [comment]
Hallo,

danke für den Tipp!

Änderung habe ich in V1.14 vorgenommen.
Ich werde meine Kontaktperson bei E3DC auch informieren.

Viele Grüße Nico
