### ISSUE TITLE
Display Auflösung

### ISSUE THREAD

**Issue by Jaynewayne** [nischram/E3dcGui#35]
Hi, das Programm funktioniert! 
Das ist echt cool
Aber leider startet es sobald ich ./start mache in so einer Art 4:3 Auflösung
Wie kann ich das ändern? gibt es irgendwo eine Datei um die Auflösung anzupassen? 
Danke schonmal für die Hilfe!
Nachtrag: Habe gerade beim beenden des Programms das gesehen: 

error opening touch screen: No such file or directory
Input device name: "Unknown"
Supported events:
Original 720x576, 32bpp
Framebuffer /dev/fb0 resolution;
720x576, 32 bpp

Ich denke nicht dass das passt. :)

**Comment by nischram** [comment]
Hey,

leider ist das Programm speziell nur für das Original Raspberry TouchDisplay 7" ausgelegt. Das Display hat eine Auflösung von 800x480. Meine Software kommt nur mit 16 bpp klar, also mit 16 Bit. Für 32Bit ist die SW nicht ausgelegt. In der Datei screenSave.c ist dafür folgendes eingebaut:
```	
//Umschalten auf 16Bit Display
char OUT[128];
snprintf (OUT, (size_t)128, "fbset -fb %s -depth 16", framebuffer_File);
system(OUT);
```
Vielleicht verwendest du eine neuere Raspberry oder Raspbain-Version die nicht mehr mit 16 Bit klar kommt. 
In der parameter.h kann für das TouchDisplay noch eingetragen werden, ggf. muss du hier die passende Framebuffer Datei z.B. `dev/fb1` eintragen und die Software erneut kompilieren.

Weitere Einstellmöglichkeiten gibt es in meiner Software nicht, somit muss die Einstellung am Raspberry vorgenommen werden.

Viele Grüße Nico

**Comment by ThomboSupergott** [comment]
Hallo Nico, 
vielen Dank für die tolle Leistung! Ich nutze auch ein Raspberry 4 mit dem 7" Touch. Kann man die Werte (Wattzahlen) der Liveansicht irgendwie größer einstellen? Meine alten Augen würden es dir danken :-)

**Comment by nischram** [comment]
Hallo,

bislang gab es in dem Programm keine Möglichkeit. 
Ich habe aber mit der Version 1.80 die Möglichkeit geschaffen. Entweder muss die Applikation upgedatet werden oder nur die Änderung hochgeladen werden. Geändert habe ich in der "GuiMain.c" eine Kleinigkeit in Bereich der Zeile 24, die Dateien "framebuffer8x16.c" und font_8x16.c" jeweils im Ordner "/Frame" sind neu. Um nun die Schriftgröße etwas zu vergrößern muss in der "parameter.h" folgende Zeile eingefügt werden:
`#define FONT_8X16`
eingefügt werden. Wenn die Schrift Normal dargestellt werden soll muss diese Zeile enthalten sein:
`#define FONT_8X8`

Leider ist durch die Gesamtstructur der Software keine stärkere Vergrößerung möglich. Aber es hilft schon ein wenig.
Ich hoffe deine Augen sehen das auch so ;-)

VG Nico

**Comment by ThomboSupergott** [comment]
Hallo Nico, 

vielen Dank, habe alles angepasst. Funktioniert :-) Meine Augen freuen sich. Echt super nett das so schnell umzusetzen. Vielen Dank.

**Comment by mafe-66** [comment]
Nachdem ich die Auflösung auf 640 x 480 runtergesetzt habe, wird auf der rechten Bildschirmseite ein Teil der Grafik angezeigt.
Wird halt dann beim neuen Laden nicht überschrieben.

![20210212_153714](https://user-images.githubusercontent.com/78905435/107781508-435a5b00-6d48-11eb-82ff-1b9f24b1c0ac.jpg)

**Comment by nischram** [comment]
Hallo zusammen,

da es in diesem Issue auch um die Schriftgröße ging, hier die Info, ich habe die GUI für die Leistungswerte nochmal geändert und nun die Schrift nochmal erheblich vergrößert. 
Siehe Issue #58 

Viele Grüße Nico
