### ISSUE TITLE
weather.tuxnet.de ist offline

### ISSUE THREAD

**Issue by JoWrusch** [nischram/E3dcGui#36]
Hallo,
das Wetter gibt es nicht mehr von weather.tuxnet24.de. Ich habe noch nicht rausbekommen, ob der Dienst nur temporär oder generell eingestellt wurde.
Weisst Du etwas darüber? So ist es schade, dass die Wetterinfo leer bleibt...
Oder hast Du evtl. schon eine Lösung? ;-)
Grüße
Joachim

**Comment by nischram** [comment]
Hallo Joachim,

ich hatte auch erst gedacht es wäre nur ein Ausfall vom Server, aber inzwischen denke ich auch, dass er dauerhaft abgeschaltet wurde.
Bislang habe ich noch keine direkte Lösung. Für weather.tuxnet24.de musste man ja schon einen Account bei OpenWeathermap.org erstellen. Für diese Seite gibt es auch eine Api, aber die löst ganz andere Antworten auf, so muss ich meine Software umbauen. 
Ich werde bei Gelegenheit mal schauen ob ich da was hinbekomme. 
Gruß Nico

**Comment by nischram** [comment]
Hallo Joachim,

Gute Nachrichten!
Ich habe die Wetteranzeige umgebaut direkt auf die API von OpenWeatherMap.org umgebaut. 
Dank der C-Weather Applikation von "https://github.com/gabrieledarrigo/c-weather" konnte ich die API einbinden.
Wie zuvor muss für die Wetteranzeige bei OpenWeatherMap.org ein Account erstellt werden, damit man einen API-Key erhält. Wenn meine Applikation mit der Wetteranzeige seit der Version V1.78 genutzt wurde sind an der "parameter.h" keine Änderungen nötig. 
Es müssen folgende Dateien aktualisiert werden:
- External/WetterGui.h
- Makefile
Neu kopiert werden muss der Ordner: 
- External/weather 
Mit den Dateien:
- External/weather/get_weather_data.h
- External/weather/jsmn.h

Viele Grüß Nico

**Comment by nischram** [comment]
Ich habe noch was vergessen:
Damit der CURL Befehl funktioniert muss auf dem Raspberry noch die CURL-Library installiert werden. Folgender Befehl ist nötig:
`sudo apt-get install libcurl4-openssl-dev`
VG Nico
