### ISSUE TITLE
S10E HM-Integration - negative Werte für TAG_EMS_ISE_POWER_NET

### ISSUE THREAD

**Issue by bs0001** [nischram/E3dcGui#37]
Hallo,

ich bekomme demnächst meinen S10E und wollte mich nun schon mal etwas vorbereiten, um dann gleich von Anfang an die Daten zu sammeln in der CCU.

Nun habe ich eine Frage zum Thema negative Werte bzgl. der POWER-Variable.
Es steht ja in diesem Projekt geschrieben, dass die Homematic keine negativen Werte auswerten kann und es daher für In und Out 2 Variablen gibt.

Ich habe mal anhand einer Testvariable die auf -20 steht im Homematic-Script einen Test gemacht und das Ergebnis war, dass bzpw. -19 größer als -20 ist.
Woher kommt diese Aussage bzw. habe ich den Sachverhalt falsch interpretiert?

Ich wollte an sich schon gerne die Werte in einer Variablen haben und kann dann mittels meiner Visualisierung (AIO Creator) entscheiden, welches Bild eingeblendet wird (Pfeilrichtung bei pos. und neg. Werten).

Viele Grüße
Bernd

**Comment by nischram** [comment]
Hallo Bernd,

die Aussage, dass die Homematic nicht mit negativen Werten arbeiten kann, ist an die Verwendung der Programme geknüpft. Wenn du mit einem Script die Programmierung übernimmst, dann geht natürlich ein negativer Wert. 

Ich hoffe die Antwort reicht.
Viel Erfolg bei deinem Projekt!
Viele Grüße Nico

**Comment by bs0001** [comment]
Hallo Nico,
Danke! Ich verstehe es leider immer noch nicht. Kannst Du es evtl an einem Beispiel verdeutlichen? Wäre super! Ich mach mir anschließend Gedanken, ob ich es dann auch mit den 2 Werten vornehme oder mit einer Variable, was mir an sich lieber wäre. Viele Grüße Bernd 
-------- Ursprüngliche Nachricht --------Von: nischram <notifications@github.com> Datum: 27.10.20  17:58  (GMT+01:00) An: nischram/E3dcGui <E3dcGui@noreply.github.com> Cc: bs0001 <bs0001@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [nischram/E3dcGui] S10E HM-Integration - negative Werte für TAG_EMS_ISE_POWER_NET (#37) 

Hallo Bernd,

die Aussage, dass die Homematic nicht mit negativen Werten arbeiten kann, ist an die Verwendung der Programme geknüpft. Wenn du mit einem Script die Programmierung übernimmst, dann geht natürlich ein negativer Wert.

Ich hoffe die Antwort reicht.

Viel Erfolg bei deinem Projekt!

Viele Grüße Nico

**Comment by nischram** [comment]
Hier ein Screen von den Einstellungen eines Programms in der HM, hier kann man als Entscheidungswert nicht -1000 eintragen, wenn dein Programm also bei einem Überschuss von 1000W starten soll warst du nicht die Netzleistung als Wert verwenden sondern musst eine eigne Variable für den Einspeisung haben.
<img width="1125" alt="Bildschirmfoto 2020-10-27 um 19 25 44" src="https://user-images.githubusercontent.com/19279623/97345626-95a36900-188a-11eb-89aa-0a4096e56b36.png">
(hier im Screen mache ich was mit Solar und nicht mit Überschuss aber das Prinzip ist gleich)

Wenn du nicht weißt ob du es in einem Programm gebrauchst oder später gebrauchst, übertrage doch einfach alle drei Werte:
- Netzleistung (+/-)
- Bezug (+)
- Einspeisung (+)

Dann kannst du die Einspeisung in Programme einbinden (ohne ein Script zu schreiben) und du kannst deine Grafiken für pos. oder neg. einblenden.
Ach ja die Frage mit dem Variablen habe ich vergessen, nein ich habe kein Script ich lege die Variablen von Hand an (so viele sind es ja nicht und das macht man ja nur ein mal).

Gruß Nico

**Comment by bs0001** [comment]
Hallo Nico,
super, Danke für die Erklärung. Ich schau mir das morgen im System mal an und stelle ggf bei Homematic einen Featurewunsch ein, dass zukünftig auch negative Werte verwendet werden können in Bedingungen. Beim Lesen Deiner Erklärung ist mir das mit den 3 Variablen auch durch den Kopf gegangen. Das ist gut, dann sollte es für alle Angelegenheiten passen. Ich werde dann die Tage mit der Installation starten und hoffen, dass meine Installation bald erfolgt.Werde dann die Datenübertragung auch erst mal auf 15 Minuten stellen. Die GUI brauche ich wahrscheinlich erstmal nicht. Habe zumindest den Standsrdscreen in AIO Creator implementiert und werde mir ausgewählte Daten noch anzeigen lassen (z. B. in einem Popup).Hab mal ein Foto angehängt, wie es ungefähr aussehen wird (aktuell habe ich irgendwelche Werte zugeordnet, damit was angezeigt wird). Bei Fragen würde ich mich einfach nochmal melden.Viele Grüße Bernd 
-------- Ursprüngliche Nachricht --------Von: nischram <notifications@github.com> Datum: 27.10.20  19:39  (GMT+01:00) An: nischram/E3dcGui <E3dcGui@noreply.github.com> Cc: bs0001 <bs0001@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [nischram/E3dcGui] S10E HM-Integration - negative Werte für TAG_EMS_ISE_POWER_NET (#37) 

Hier ein Screen von den Einstellungen eines Programms in der HM, hier kann man als Entscheidungswert nicht -1000 eintragen, wenn dein Programm also bei einem Überschuss von 1000W starten soll warst du nicht die Netzleistung als Wert verwenden sondern musst eine eigne Variable für den Einspeisung haben.



(hier im Screen mache ich was mit Solar und nicht mit Überschuss aber das Prinzip ist gleich)

Wenn du nicht weißt ob du es in einem Programm gebrauchst oder später gebrauchst, übertrage doch einfach alle drei Werte:



Netzleistung (+/-)

Bezug (+)

Einspeisung (+)



Dann kannst du die Einspeisung in Programme einbinden (ohne ein Script zu schreiben) und du kannst deine Grafiken für pos. oder neg. einblenden.

Ach ja die Frage mit dem Variablen habe ich vergessen, nein ich habe kein Script ich lege die Variablen von Hand an (so viele sind es ja nicht und das macht man ja nur ein mal).

Gruß Nico

**Comment by bs0001** [comment]
Hallo Nico,

 

ich habe mal etwas rumgespielt. Das Skript hatte es anfangs nicht annehmen wollen, aber als ich zuerst einen Wertebereich von bis im negativen Bereich eingestellt hatte, lies er mich anschließend auch die unteren Radiobuttons auswählen, ohne dass es nach Bestätigung einfach wieder auf 0 gesetzt wird.



 

Kannst es ja gerne auch mal probieren.

Das müsste doch genau dieser Punkt sein, wenn das funktioniert, dass man dann mit nur einer Variable arbeiten kann, oder?

 

Gerne mache ich bei eq3 ein Ticket als Verbesserungswunsch auf, dass dies gleich funktioniert auch ohne Eingabe eines von bis Bereiches.

 

Viele Grüße 

Bernd 

 

 

Von: nischram <notifications@github.com> 
Gesendet: Dienstag, 27. Oktober 2020 19:39
An: nischram/E3dcGui <E3dcGui@noreply.github.com>
Cc: bs0001 <bs0001@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [nischram/E3dcGui] S10E HM-Integration - negative Werte für TAG_EMS_ISE_POWER_NET (#37)

 

Hier ein Screen von den Einstellungen eines Programms in der HM, hier kann man als Entscheidungswert nicht -1000 eintragen, wenn dein Programm also bei einem Überschuss von 1000W starten soll warst du nicht die Netzleistung als Wert verwenden sondern musst eine eigne Variable für den Einspeisung haben.
 <https://user-images.githubusercontent.com/19279623/97345626-95a36900-188a-11eb-89aa-0a4096e56b36.png> 
(hier im Screen mache ich was mit Solar und nicht mit Überschuss aber das Prinzip ist gleich)

Wenn du nicht weißt ob du es in einem Programm gebrauchst oder später gebrauchst, übertrage doch einfach alle drei Werte:

*	Netzleistung (+/-)
*	Bezug (+)
*	Einspeisung (+)

Dann kannst du die Einspeisung in Programme einbinden (ohne ein Script zu schreiben) und du kannst deine Grafiken für pos. oder neg. einblenden.
Ach ja die Frage mit dem Variablen habe ich vergessen, nein ich habe kein Script ich lege die Variablen von Hand an (so viele sind es ja nicht und das macht man ja nur ein mal).

Gruß Nico

**Comment by nischram** [comment]
Hallo Bernd,

eventuell hatte ich dann seinerzeit was falsch gemacht oder es ist inzwischen auch ein negativer Bereich möglich, aber ich hatte es für meine Überschussverbraucher nicht hinbekommen. Vielleicht lag es auch an dem was du rausbekommen hast.

Ich finde es nicht tragisch drei Variablen zu haben, Ist zum Teil auch verständlicher. Nicht umsonst sind es bei meiner Homematic 248 Variablen. 
Bei einem push alle 30 Sekunden wird es in der Auslastung auch nicht zu merken sein. 

Gruß Nico
