### ISSUE TITLE
S10E - Weitere Datenpunkte

### ISSUE THREAD

**Issue by bs0001** [nischram/E3dcGui#39]
Hallo Nico,

E3DC liefert für den E3DC ja diverse Datenpunkte:
https://www.e3dc.com/wp-content/uploads/2020/04/KNXConnect-Datapoints.xml

Durch Erweiterung der parameter.h und vorheriger Erfassung der Variablen in der CCU können diese noch ergänzt werden, oder?

Hast Du vor, alle verfügbaren Variablen noch zentral in das Projekt hier aufzunehmen oder soll es individuell jeder Nutzer selbst vornehmen?

VG
Bernd

**Comment by nischram** [comment]
Hallo Bernd,

deine Anleitung die du gefunden hast bezieht sich auf das KNX Modul, das hat nix mit RCSP zutun. Meine Applikation basiert auf der RSCP-Schnittstelle. Im Download bei E3DC gibt es bei der Beispielapplikation eine Excel-Liste mit TAGs. In der Liste haben ich für mich keine Relevanten Daten mehr gefunden. Ich werde bei mir nicht, ohne das ich es an meiner Anlage testen kann, weitere Punkte aufnehmen, denn dann müsste ich meine Software ungetestet veröffentlichen und das ist nich Sinnvoll. 
So werde ich aktuell nichts erweitern, es sei in der Liste gibt es was neues Lebensnotwendiges.

Gruß Nico

**Comment by bs0001** [comment]
Hallo Nico,

nachdem meine Anlage nun läuft, die Batterie initialisiert wurde muss nun mal die Sonne rauskommen, damit ich erste Ergebnisse sehen kann.
Habe mich weiter mit dem Thema hier beschäftigt und würde gerne weitere Werte mir anzeigen lassen.
Von daher wollte ich nachfragen, ob diese Vorgehensweise so korrekt ist oder ob ich was vergessen habe.

Ziel ist es, weitere Werte aus dem S10 E in der CCU anzuzeigen.
Wie beschrieben habe ich dazu im Servicebereich die entsprechenden Infos gefunden, auch was die Datenpunkte betrifft.
Das ist schon mal ziemlich gut zu sehen. Zeigt einem ja, was maximal zur Verfügung steht.


Ich möchte bspw. gerne die Zyklenanzahl (TAG_BAT_CHARGE_CYCLES) der Batterien (ich habe 2 Stück drinnen, angeschlossen jeweils an einem eigenen Batteriekreis) oder aber die Batterietemperatur (TAG_BAT_MAX_DCB_CELL_TEMPERATURE) auslesen.
Oder aber auch Fehlermeldung/Statusmeldungen (TAG_EMS_ERROR_MESSAGE). Damit könnte ich mich sofort aktiv per Mail informieren lassen, wenn die Anlage was meldet.


Hierzu müsste ich doch folgendes tun, oder?

1) Erweiterung RscpMain.cpp um die jeweiligen Werte
![image](https://user-images.githubusercontent.com/46260437/102022351-99ca0e00-3d86-11eb-8579-2170bdbf22d7.png)
Einen Block wie in Zeile 345 (TAG_BAT_RSOC) für die beiden benannten Werte anlegen.
Wie allerdings kann ich auf Batteriekreis 0 und 1 zugreifen? Momentan dürften die wahrscheinlich sogar gleich sein. Falls ich aber zukünftig noch eine dazu stecke, dann kommen die beiden jetzigen in einen Batteriekreis und die neue in den anderen.

2) Im Verzeichnis Rscp in der Datei RscpTags.h habe ich gesehen, dass dort die ganzen Tags schon enthalten sind. Also kein ToDo.

3) Anlegen der Variablen in der CCU und Ermittlung der ISE-Ids.

4) Erweiterung der parameter.h
In diesem Bereich müssten genau die o.g. Tags dann mit Zuordnung der ISE aufgeführt werden:
![image](https://user-images.githubusercontent.com/46260437/102022491-87040900-3d87-11eb-8c51-5080ea274885.png)

5) Projekt neu generieren mittels make

Das müsste es gewesen sein, oder?

Ich werde es gerne ausprobieren und stelle das Ergebnis auch gerne zur Verfügung.


Grüße
Bernd

**Comment by nischram** [comment]
Hallo Bernd,

Grundsätzlich bist du auf dem richtigen Weg. Punkte 1. bis 5. sind soweit korrekt. 
Jetzt könnte es nur Probleme mit dem Wert geben. Einige Werte der Batterien werden als Summe oder Gesamtwert angezeigt die sind von der Abfrage wie oben angegeben, aber andere werden nur je Batteriemodul ausgegeben. So muss man diese Werte in mehreren Abfragen oder mehrere Durchläufen auslesen. Ähnlich musste es mit den Spannungen und Leistungen bei den zwei Trackern gemacht werden. Da könntest du dir das Prinzip ansehen. Wie es bei einem S10-PRO mit dem zwei Batteriekreisen funktioniert weiß ich nicht denn meine S10-E hat nur einen Kreis, das kann ich nicht testen.

VG Nico

**Comment by bs0001** [comment]
Hallo Nico,
pünktlich zum Weihnachtsfest habe ich nun einige Ergänzungen vorgenommen.
U.a., Produktionsdatum, Notstrominfos, Batterienzyklen, Batterientemperatur, Anz. Batterien, Trainingsmode
Habe meine Anpassungen alle mit "BS" in der RscpMain.cpp kommentiert.

Folgende Sachen habe ich bislang noch nicht rausgefunden:

**1. Zugriff auf die einzelnen Batteriewerte**
Habe zahlreiche Versuche mit index und container auf den entsprechenden Rückgabetag gemacht, aber der Inhalt war immer leer. Hatte mich da an dem Beispiel ab Zeile 523 orientiert im TAG_PVI-DATA. Leider hats irgendwie nicht funktioniert. Vielleicht hast Du da noch eine Idee.
![image](https://user-images.githubusercontent.com/46260437/103096298-ce9a5880-4603-11eb-995f-17d2602d9822.png)

**2. Auslesen TAG_EMS_ERROR_MESSAGE**
Ich würde gerne zyklisch abprüfen, ob es Fehlermeldungen gibt. Falls welche vorhanden sind, würde ich gerne die Fehlerinfo auslesen. Leider habe ich zum Auslesen des Tags TAG_EMS_ERROR_MESSAGE keinen TAG mit dem Kürzel REQ gefunden.
Das hier hat auf jeden Fall mal nicht funktioniert:
![image](https://user-images.githubusercontent.com/46260437/103096408-246f0080-4604-11eb-900c-164b4636f504.png)

**3. Abfragevarianten (Idee)**
Ich weiß nicht, ob es der Anlage zu viel Stress bereitet, wenn man immer alle Werte abfrägt. Ich würde gerne im Rahmen einer Gruppierung festlegen, welche Daten sehr oft gelesen werden (also sekündlich die Leistungsdaten, wie das jetzt schon ist) und welche Daten seltener gelesen werden (Seriennr., Produktionsdatum ...) ändern sich ja nicht oft bzw. gar nicht.

Damit Du mal ein Bild bekommst, wie das bei mir in der App so aussieht, hier mal ein paar Screenshots.
![image](https://user-images.githubusercontent.com/46260437/103096643-e7573e00-4604-11eb-8b25-aee7f63905a9.png)
![image](https://user-images.githubusercontent.com/46260437/103097069-597c5280-4606-11eb-8b0b-47efc6d61b60.png)
![image](https://user-images.githubusercontent.com/46260437/103097083-6600ab00-4606-11eb-9210-afd5e2713886.png)

Info bzgl. der Übertragung von Texten an die Homematic:
z.B. wenn ich die Info-Felder Trainings Mode und Emergency Mode an die HM-Variablen übertragen möchte, muss ich die im Text befindlichen Leerzeichen durch %20 ersetzen. Ist beim Schreiben von PHP in die HM-Variablen auch so. Damit funktioniert es dann. Ansonsten wird nichts geschrieben, wenngleich es aussieht, dass die Variablen geschrieben werden.

Anbei auch die RscpMain.cpp, wenn Du Dir diese mal ansehen möchtest.

Was mir generell noch aufgefallen ist (hat aber nichts mit dem Projekt hier zu tun), dass Nachts zwischen 1 und 3 Uhr der Ladestand der Batterien mal 0% übermittelt, auch wenn diese noch einen Füllgrad haben. Konntest Du sowas auch schon feststellen?

Echt ein tolles Projekt! Wenn man sich reingearbeitet hat und die Funktionsweise verinnerlicht und hoffentlich verstanden hat, geht es ganz gut, Ergänzungen vorzunehmen.
Die neu hinzugefügten Daten habe ich nicht in den RAM-Disk geschrieben. Mir hat es ausgereicht, wenn diese in der HM ankommen und ich diese von dort weiterverarbeiten kann.


[RscpMain_20201224.zip](https://github.com/nischram/E3dcGui/files/5740075/RscpMain_20201224.zip)

In diesem Sinne, ein schönes Weihnachtsfest
Bernd

**Comment by bs0001** [comment]
Hi Nico,

ich bin dabei nun das E3dGui vom Raspi auf die DiskStation zu überführen. In dem Zuge wollte ich dann auch gleich auf die aktuellste Version von Dir umsteigen und meine Ergänzungen wieder einbauen (hab ja da noch ein paar Sonderlocken eingebaut).

Das Thema Auslesen der Batterie wollte ich gerne nochmal aufgreifen.
Vielleicht kannst Du bei Gelegenheit ja doch die Batteriewerte der einzelnen Batterien mit auslesen, so dass man diese in die Homematic-Variablen wegschreiben kann. Insbesondere Temperatur, Degradation, Ladezyklen, Status wären da interessant, evtl. auch noch der eine oder andere Wert.
Im Projekt rscpgui kann man sich die einzelnen Batterieinfos auch je Batteriekreis anzeigen lassen.
Wäre sehr schön, wenn das hier im Programm auch noch mit reinkommen würde.

Viele Grüße
Bernd
