### ISSUE TITLE
Echtzeit-Anzeige S10E Informationen in AIO Creator NEO

### ISSUE THREAD

**Issue by bs0001** [nischram/E3dcGui#40]
Hallo Nico,

ich nutze als Frontend für die Heimautomatisierung das Projekt piVCCU3 auf einem Raspi Model 3B+, habe dort drauf auch einen PHP-Server am laufen um meine Weichwasseranlage auszulesen und zu steuern und habe die Visualisierung über AIO Creator NEO vorgenommen.
Als PlugIn habe ich nur die CCU, was bislang auch ausreicht. IP-SYSCON o.ä. wollte ich nicht noch zusätzlich kaufen müssen.
Einen AIO Gateway habe ich auch nicht.

Die Daten des S10E speichere ich zukünftig dann ja alle 15 Minuten in der CCU.
Ich möchte aber gerne noch die aktuellen Leistungswerte, die sekündlich abgerufen werden können auf meiner Fernbedienungsseite im AIO Creator Neo anzeigen lassen.
Ich dachte mir, dass ich die anzuzeigenden Variablen dann direkt per Skript abrufe.

Hier der Hinweis auf die Doku:
https://doku.mediola.com/doku.php?id=de:creator:ui-remote-status-http

https://doku.mediola.com/doku.php?id=de:creator:start

Ich stelle mir nun die Frage, wie ich mit Deinem Framework das realisieren kann. Für die Display-Variante in Deinem Projekt machst Du ja was ähnliches.

Ich habe mal einen Screenshot zur Verdeutlichung angehängt, wie ich mir das mit der Visualisierung vorstelle.

VG
Bernd

![AIO Creator - E3DC S10E Integration](https://user-images.githubusercontent.com/46260437/97975338-48168700-1dc9-11eb-8142-ccbc1a123a68.jpg)

**Comment by nischram** [comment]
Hallo Bernd,

ich nutze und kenne Mediola oder das AIO nicht. So kann ich bei deiner Überlegung nicht helfen. 
Nur ein Tipp: Vielleicht ist Modbus eine Option.

VG Nico
