### ISSUE TITLE
RAM Disk Daten sichern vor geplantem Reboot

### ISSUE THREAD

**Issue by bs0001** [nischram/E3dcGui#41]
Es kann ja mal sein, dass ich den Raspi neu starten muss.
Was wäre denn zu tun, damit die Daten, die sich im RAM Disk befinden nicht verloren gehen?
Gibt es ggf. hierzu auch ein Skript, das man vor einem geplanten Neustart ausführen sollte?

Wo kann ich sehen, wann das letzte Mal Daten aus dem RAM Disk weggeschrieben wurden?
Wäre vielleicht hilfreich, was die Größe der RAM Disk Partition betrifft.
Es kommt schon mal vor, dass der Raspi hängen bleibt und vom Stromnetz getrennt werden muss.

**Comment by nischram** [comment]
Es tut mir leid, da verlangst du jetzt etwas viel von meiner Software.
Die Leitungswerte werden nur für 24h dargestellt, sind dafür im RAMDisk und werden nicht gespeichert. Wenn der Pi neu startet beginn das Aufzeichnen von vorne.
Um das schöner zu machen gibt es andere Applikation, die ich z.B. verlinkt habe.

**Comment by bs0001** [comment]
Hallo Nico,
es ging mir nicht darum, dass Deine Software hier eine Erweiterung haben sollte. Mir ging es eher darum folgende Sachen zu verstehen:

1. Ramdisk
Den habe ich eingerichtet. Sofern ich den Raspi neu starte, wären die darin gespeicherten Infos ja weg.
Wenn es ein Shell-Script oder Befehl gibt, den ich in mein Reboot-Script noch mit einbauen könnte, der die Daten aus dem Ramdisk noch wegschreibt, dann ginge ja nicht wirklich was an gesammelten Daten verloren.

2. Nutzung Ramdisk
Der Ramdisk wird doch für alle auf dem Raspi vorhandenen Applikationen, die laufen verwendet und nicht ausschließlich für E3dcGui, oder? Die Installation habe ich so durchgeführt, wie es in Deiner Anleitung stand.

3. Füllstand Ramdisk
Wenn die 8MB ausgeschöpft sind, schreibt er automatisch die Daten weg, oder? Mit dem Befehl df kann man sich das ja ansehen. Bei mir sind akt. 40kb benutzt von 8192kb.

Grüße
Bernd

**Comment by nischram** [comment]
Hallo Bernd,

Zu 1: Klar könnte man ein Script schreiben um die Daten zu speichern und später wieder zurückzuholen, aber im späteren Betrieb wirst du da nicht zu kommen. Gefühlt habe ich alle halbe Jahre mal was warum ich den Pi neu starte und das nicht wegen meiner Applikation sondern wegen dem AirPlay was ich zusätzlich auf dem Pi nutze.

Zu2: Genau die RAMDisk die in meiner Applikation gebraucht wird, wird nicht von anderen genutzt sonst hättest du die ja nicht einrichten müssen. Meine Applikation nutz die RAMDisk mehrfach aber nur für die Leistungskurven gehen ggf. Daten verloren. Dafür lohnt der Aufwand nicht.

Zu 3. die Kurven benötigt für 24h in 15Min-Werten keine Datenmenge und das ist somit Ringpuffer und das RAMDisk wird nicht voll, wenn doch stürzt der Pi ab.

Gruß Nico
