### ISSUE TITLE
S10_EMS_POWER_GRID - negativen Wert abspeichern

### ISSUE THREAD

**Issue by bs0001** [nischram/E3dcGui#43]
Was muss ich verändern, damit in der Variable S10_EMS_POWER_GRID ein negativer Wert eingetragen wird, wenn ich Strom aus dem Netz beziehe

**Comment by nischram** [comment]
Die Frage ist unlogisch! Jeder Zähler von deinem Stromanbieter zählt Bezug positiv und Einspeisung negativ. So ist es nicht vorgesehen. Ansonsten muss du dich halt selber mit dem Quellcode beschäftigen.

**Comment by bs0001** [comment]
... Du schreibst doch [hier](https://github.com/nischram/E3dcGui/tree/master/Homematic), dass NET_IN und NET_OUT verwendet wird, da Homematic in Programmen nicht mit negativen Werten umgehen kann. Ich hatte ja rausgefunden, dass es geht. Von daher hätte ich gerne den positiven oder negativen Wert in eine Variable geschrieben.
Habe mir dazu die Variable "S10_EMS_POWER_NET" angelegt, dann aber gesehen, dass es die Variable "S10_EMS_POWER_GRID" bereits gibt, die scheinbar genau diesen Wert widerspiegelt.
Ich bekomme hier aber nur positive Werte. Kann auch gerne so bleiben,
Ich hätte dann allerdings in meine Variable "S10_EMS_POWER_NET" einen positiven Wert, wenn ich Strom ins Netz einspeise und einen negativen Wert, wenn ich Strom aus dem Netz beziehe.
Ich hoffe, ich hab das nicht gänzlich falsch verstanden.

**Comment by bs0001** [comment]
Hallo Nico,

ich habe mir das Coding im RscpMain.cpp nochmal genau angesehen.
![image](https://user-images.githubusercontent.com/46260437/101236275-295d2600-36d0-11eb-8183-6b0a84736aff.png)

Hier passiert ja genau das, was ich benötige (hoffe ich zumindest). Kann es aktuell noch nicht testen, da meine PV-Module noch nicht angeschlossen sind und daher aktuell nur Strom aus dem Netz bezogen wird.
Wenn ich es richtig verstanden habe, dann erhalte ich in der Variable "TAG_EMS_OUT_POWER_GRID" einen positiven Wert, wenn ich Strom aus dem Netz beziehe und einen negativen Wert, wenn ich Strom ins Netz einspeise. Genau so steht es auch in der ModBus-Anleitung V1.70. 
![image](https://user-images.githubusercontent.com/46260437/101236308-7fca6480-36d0-11eb-89b3-1828641b5721.png)

Das einzige, was ich nun noch angepasst habe, war die Systemvariable in der HM.
Die Variable S10_EMS_POWER_GRID habe ich noch wie folgt -65000 und 65000 angepasst.

Sobald es mal soweit ist und eine Einspeisung stattfindet (wo ist bloß die Sonne?), kann ich gerne berichten, ob es funktioniert. Kannst mir aber auch gerne eine Rückmeldung geben, wenn mein angedachter Weg richtig oder falsch ist.

Viele Grüße
Bernd

**Comment by nischram** [comment]
Hey,

ich denke wenn du die PV dann aktiv hast und das erste mal Überschuss ins Netz gibst wird du sehen das es schon genau das mach was du möchtest. 
Hier nochmal erklärt:
![101236275-295d2600-36d0-11eb-8183-6b0a84736aff](https://user-images.githubusercontent.com/19279623/101285650-ab3f7300-37e6-11eb-9a9d-34041e99797d.png)
In Gelb:
hier wird der Netzbezug positiv in "Net_Out" angegeben und in der Zeit ist "Net_In" 0
In Rot:
hier wird der Netzeinspeisung positiv in "Net_In" angegeben und in der Zeit ist "Net_Out" 0
In Grün:
hier wird beides ausgegeben der Netzbezug ist positiv und die Netzeinspeisung dann negativ.

Wenn du es umdrehen willst, musst du im grünen Bereich eine Umrechnung mit  `* -1` vornehmen. Grundsätzlich passt das dann aber nicht zu allen anderen Anzeigen und Ausgaben. Denn der Standard ist wie oben schon mal geschrieben, so dass der Netzbezug positiv und die Einspeisung negativ, angezeigt werden.

Gruß Nico

**Comment by bs0001** [comment]
Hi Nico,
Danke nochmal für die ausführliche Info!
Habe es bei mir auch so eingerichtet, dass Einspeisung negativ ist und Netzbezug positiv. Es soll alles konsistent sein.
Von daher freue ich mich schon auf die Ergebnisse.
Ich hoffe, dass die PV-Module nächste Woche angeschlossen werden. Anfang Januar möchte ich dann die finale Inbetriebnahme mit dem Netzbetreiber machen. Dann bekomme ich auch Einspeisewerte, wenn genügend Sonne aufs Dach kommt.
Viele Grüße
Bernd
