### ISSUE TITLE
Aktuelle Tageswerte in HM Systemvariablen schreiben

### ISSUE THREAD

**Issue by bs0001** [nischram/E3dcGui#44]
Hallo,
ich habe Homematic Systemvariablen angelegt für die Tageswerte.
Habe mir auch schon S10history angesehen, komme damit allerdings nicht so ganz klar.
Gerne würde ich Tageswerte, aber auch gerne Monats und Jahreswerte abrufen können und in die Systemvariablen schreiben.
Habe bspw. für Solarproduktion, Eigenstrom, Netzeinspeisung, Netzbezug, Hausverbrauch, Batterie laden, Batterie entladen eine angelegt.
Mir ist allerdings nicht klar, wie ich durch Anpassung des Skripts die Daten in die Systemvariablen schreiben kann.
Wäre prima, wenn Du hierauf eingehen könntest.
Ansonsten läuft nun die Ermittlung. Habe seit gestern den S10 E Pro erhalten.
Klasse Implementierung von Dir!!
Grüße
Bernd

**Comment by nischram** [comment]
Warum eröffnest du hier am laufenden Band Issues obwohl keine Fehler anliegen. Ich war beim letztem Mal schon am überlegen ob ich überhaupt Antworte, habe es aber dennoch sehr ausführlich gemacht und jetzt eröffnest du zum selben Thema ([Issue#42](https://github.com/nischram/E3dcGui/issues/42)) eine neuen Issue. Wie schon im anderen Beitrag erwähnt sehe ich in meine Software keine Möglichkeit Monats- und Jahreswerte einzubauen. Da passt die Abfragerate einfach nicht. Du solltest eine andere Applikation parallel installieren und für dich einrichten.

**Comment by bs0001** [comment]
... sorry, tut mir leid mit den Issues! Ich hatte keinen Weg gefunden, Dich direkt anzuschreiben für meine Fragen. Mache ich gerne so, da es wie Du richtig geschrieben hast keine echten Issues sind, bis auf das eine mit den neg. Werten, was ich rausgefunden hatte. Gib mir bitte bescheid, dann nehme ich einen anderen Weg der Kontaktaufnahme - ich kann ihn hier beim Besten Willen nicht finden. Ich will das hier auch nicht vollspamen. Ich werde zukünftig für Fragen auch keine Issues mehr einstellen.
An dieser Stelle aber vielen Dank für Deine Hilfsbereitschaft und für die Applikation, die Du hier bereitstellst. Das gefällt mir echt sehr gut!
