### ISSUE TITLE
Wetterdaten werden nicht geladen

### ISSUE THREAD

**Issue by nischram** [nischram/E3dcGui#47]
Hallo Nico,
nur wenn ich B4 als Startmodus eingebe, ist nach 60 Sekunden alles OK. Bei B2 bleibt die Console ständig im Hintergrund. Deine Empfehlungen teste ich noch mal.
Zu dem Wetter: bekomme ich die Meldung im Browser: "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info." wenn ich das mit deinem Link teste. Mit dem Link aus der openweater Seite: api.openweathermap.org/data/2.5/weather?id={city id}&appid={API key} kann ich Daten abrufen. Ich habe "nur" diesen kostenfreien Openweater Account erstellt. 
Gruß Thomas

_Originally posted by @dg0ovp in https://github.com/nischram/E3dcGui/issues/46#issuecomment-765571377_

**Comment by nischram** [comment]
@dg0ovp 
Hallo Thomas, 

es schein so als hat "OpenWeatherMap" die Bedingungen für neue User geändert, aber die schon bestehenden User scheinen nicht betroffen zu sein.
<img width="609" alt="Bildschirmfoto 2021-01-24 um 17 55 29" src="https://user-images.githubusercontent.com/19279623/105637667-de10f980-5e6e-11eb-9c82-f5d90ad66475.png">
<img width="501" alt="Bildschirmfoto 2021-01-24 um 18 10 35" src="https://user-images.githubusercontent.com/19279623/105637792-8aeb7680-5e6f-11eb-8c48-418a9b7f48a7.png">
So wie es auf die Schnelle für mich aussieht muss ich eventuell die Abfrage umbauen. Zu der Zeit wo ich auf "OpenWeatherMap" umgestellt habe gab es meines Wissens die Abfrage mit "oncecall" nicht. 

Hier werde ich aber einige Zeit gebrauchen, weil ich aktuell nur begrenzt Zeit dafür habe.
Ich hoffe es hat etwas Zeit.

VG Nico

**Comment by dg0ovp** [comment]
Hallo Nico,
das mit den Werten des Hauskraftwerks war das eigentliche Ziel des Displays. Das mit dem Wetter hat also Zeit bis zur Umsetzung. Ich habe dieses Issue jetzt mal aboniert, damit ich eine Info bekomme wenn du so weit bist und dann dies dann gerne teste.
Gruß Thomas

**Comment by nischram** [comment]
Hallo Thomas, 
Ich habe den neuen "OneCall" Code der OpenWeatherMap API eingebaut. Mit meinen Zugangsdaten geht es. Du kannst es ja mal testen.
Für die Änderungen musst du einige Zeilen in der "parameter.h" ändern und die Dateien "External/WetterGui.h" und "External/weather/get_weather_data.h" austauschen.

Gruß Nico

**Comment by dg0ovp** [comment]
Hallo Nico,
grundsätzlich schenit die neue Abfrage zu funktionieren. Jedoch glaube ich die Parameter für Longitude und Latitude sind vertauscht. Denn wenn ich dies in die parameter.h Eingebe #define WEATHER_LON       "8.0167" und #define WEATHER_LAN   "50.4"  kommt eine Temperaturanzeige von 22°C und 03:58 Uhr Sonnenaufgang. Beim Blick aus dem Fenster schneit es draußen gerade. Vertausche ich die beiden Werte erscheint eine Anzeige die ganz OK aussieht. 
Zukünftig wäre es toll in die Anleitung oder als Kommentar der Parameter Datei noch eine Erklärung hinzuzufügen wo man diese Werte finden kann. Der Parameter  WEATHER_LAN sollte doch  WEATHER_LAT heißen oder habe ich das falsch verstanden?
Gruß Thomas

**Comment by nischram** [comment]
Hallo,

ja da hatte sich der Fehlerteufel eingeschlichen. Im CURL Befehl habe ich die beiden Werte vertauscht eingetragen, gemerkt habe ich das bei mir nicht weil meine Koordinaten habe ich auch vertauscht eingetragen gehabt. Mit LAT statt LAN hast du natürlich recht, habe ich jetzt angepasst. Die parameter.h musst du nochmal anpassen und die "External/weather/get_weather_data.h" austauschen.
Die Zeilen in der parameter.h hatte ich schon mal hinzugefügt, aber dann muss ich die ganze README jedesmal ändern wenn sich eine Zeile verschiebt. Ich denke, dass man mit einer Suche wie mit Strg + F diese Info auch herausfinden kann.

Viele Grüße Nico
PS: deinen letzten Beitrag habe ich mal geändert denn du solltest keine Koordinaten von dir öffentlich stellen.

**Comment by dg0ovp** [comment]
Hallo,
jetzt habe ich die Änderungen testen können. Für mich sieht das jetzt gut aus. Das Issue kann geschlossen werden.
Mit dem Kommentar zu der Paramaeter Datei meinte ich nicht wo man die Werte für Longitude und Latitude in der Datei findet, sondern wo man diese Werte für seinen Ort findet. 
Danke fürs aufpassen und editieren meiner Standortangeben im letzten Post, aber ich hatte die Werte schon so gewählt das Sie nur in die Nähe meines Ortes zeigen.
Gruß Thomas

**Comment by nischram** [comment]
Hey Thomas,
super danke fürs Feedback.
Oh sorry, da habe ich dich tatsächlich wohl total falsch verstanden.
Ich habe dafür auch keine so richtige Möglichkeit. Ich gehe immer auf Google-Maps, suche mir die Position und gehe mit Rechtsklick auf "Was ist hier?" und dann sind unten oft Koordinaten. 
Aber ein guter Hinweis, vielleicht finde ich ja noch eine einfache Option die Koordinaten zu finden, dann werde ich es in die Anleitung aufnehmen
Ok dann mache ich den Issue mal zu. Wenn du weitere Fragen hast melde dich gerne wieder.
Viele Grüße Nico
