### ISSUE TITLE
GUI nur teilweise sichtbar

### ISSUE THREAD

**Issue by mafe-66** [nischram/E3dcGui#48]
Hallo Nico,

auch von mir erstmal herzlichen Dank für die Erstellung und die Anleitung für die Steuerung einer HomeMatic mit einer E3DC Photovoltaikanlage.
Die HomeMatic haben wir letztes Jahr in Betrieb genommen. Die E3DC Photovoltaik mit Speicher wurde dieses Jahr eingeschaltet.
Bei der Installation von E3dcGui bin ich auf die gleichen Probleme gestoßen, wie unten geschildert.
HIer ist ein Raspberry 4 mit einem 7" Raspberry Touchscreen im Einsatz.
Desktop ist abgeschaltet und Cursor + Bildschirmschoner sind gem. Anleitung deaktiviert.
Trotzdem sind nur die Felder mit den variablen Werten dauerhaft auf dem schwarzen Hintergrund sichtbar. Die Schaltflächen und Grafiken blinken ab und zu kurz auf und verschwinden dann wieder.
Gibt es hierzu bereits einen neuen Lösungsansatz?

Grüße,

Markus

------------------------------------------------------------------------------------------------------------------

Hallo Thomas,

nachdem mir der Gedanke kam, dass ich schon den glichen Fehler hatte, habe ich auch eine mögliche Lösung gefunden. 
In meiner Anleitung habe ich es hier beschrieben:
[https://github.com/nischram/E3dcGui#desktop-deaktivieren](https://github.com/nischram/E3dcGui#desktop-deaktivieren)
Hier geht es darum die Standard Oberfläche "startx" vom Raspberry abzustellen, damit keine ungewollten Ausgaben auf dem Display zu sehen sind. 
Zur Erklärung: das Hintergrundbild wird nur von Zeit zu Zeit neu geschrieben, wenn nun die Oberfläche dazwischenfunkt wird der Hintergrund schwarz und man sieht nur noch die Werte die alle paar Sekunden neu geschrieben werden.
 
Ggf. muss nicht nur der Desktop deaktiviert werden, sonder zusätzlich auch der Cursor und der Bildschirmschoner deaktiviert werden, dies findest du hier:
[https://github.com/nischram/E3dcGui#wichtig-pi-bildschirmschoner-deaktivieren](https://github.com/nischram/E3dcGui#wichtig-pi-bildschirmschoner-deaktivieren)

Ich hoffe es klappt, aber ansonsten musst du dich nochmal melden.
Viel Erfolg
Gruß Nico

_Originally posted by @nischram in https://github.com/nischram/E3dcGui/issues/46#issuecomment-763853316_

**Comment by nischram** [comment]
Hallo Markus,

schade, dass die Installation nicht mehr auf Anhieb klappt.

Im Moment gehe ich davon aus, dass es mit Raspberry Pi 4 zu tun hat oder mit der neusten Software.
Ich habe auf meinem Raspberry seit Ewigkeiten kein Update gemacht, ich werde das mal machen und schauen was passier.

Damit wir die Versionen nach meinem Versuch vergleichen können kannst du ja schon mal deine Versionen hier Posten. Bitte verwende folgende Abfragen und sende mir die Ausgaben.
```
cat /etc/os-release
```
```
uname -a
```
```
vcgencmd version
```

Ich melde mich dann wieder, wenn ich bei mir das Update gemacht habe und ein Ergebnis habe.

Viele Grüße Nico

**Comment by mafe-66** [comment]
Hallo Nico,

hier das Ergebnis der Abfragen.
![Screenshot_20210211-210003_OnlineStorage](https://user-images.githubusercontent.com/78905435/107691880-53bcf800-6cac-11eb-80ed-57c633f6e9c1.jpg)
ich hoffe, das hilft weiter.

Grüße,

Markus

**Comment by nischram** [comment]
Hey,
ich bekomme meinen Pi nur nach:
`Linux raspberrypi 4.19.66`
Ich habe gelesen, dass das Standard Update nur die letzte stabile Version aufspielt. Da ich den Raspberry auch für andere Dinge nutze, werde ich jetzt lieber die Tests mit einer anderen SD-Karte machen. Da werde ich aber wohl erst am Wochenende zu kommen. Wenn ich dann auch nach 5.10 komme kann ich schauen ob der Fehler bie mir auch auftritt.

Gruß Nico

**Comment by dg0ovp** [comment]
Hallo,
bei mir war dies mit einem Raspberry 3 aufgetrten. An dem 4er Modell liegt es dann wohl nicht. Nur zur Info.
Gruß Thomas.

**Comment by nischram** [comment]
Hallo Thomas,
sehr gut Danke für die Info. Kannst du eventuell auch mal die Version auslesen mit:
```
uname -a
```
Dann hätte ich noch einen Vergleich mehr.

Danke Gruß Nico

**Comment by dg0ovp** [comment]
Hallo Nico,
meine Version ist:
5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux
Gruß Thomas

**Comment by nischram** [comment]
Hallo Markus,
hallo Thomas,

nach langer Suche habe ich es gefunden. 
Der Grund lagt an meinem Tool um die Bilder darzustellen. Es scheint mit der neuen Raubein-Version Probleme zu machen. 
Ich konnte den Fehler umgehen in den ich eine Fehlerabfrage ausgeschaltet habe. Ich habe keine negative Auswirkung dadurch festgestellt.
Geändert habe ich die "/Frame/DrawImage.h"

Zusätzlich habe ich bei der Aktion auch noch Kleinigkeiten an der "Watchdog.cpp" und an der "GuiMain.c" vorgenommen.
Auch ist mit aufgefallen, dass der Touch sich nicht mitgedreht hat. In der StepByStep habe ich zuvor einen Link gehabt der vorgibt in der `sudo nano /boot/config.txt` die Zeile `display_rotate=2` einzufügen. Dieser Befehl dreht den Touch nicht mit, der Touch wird mitgedreht wenn man `lcd_rotate=2` eingibt. Eventuell ist das auch eine Änderung seit der neuen Raubein Version denn zuvor war mir das noch nicht aufgefallen.

Ihr könnt ja mal Testen, vielleicht klappt es ja jetzt Problemlos bei euch.

Viele Grüße

**Comment by mafe-66** [comment]
Hallo Nico,

die modifizierten Dateien habe ich aktualisiert.
Nach erneuter Eingabe von "make" im Verzeichnis /E3dcGui und anschließendem Neustart erscheint di Grafik.
Bei der Abarbeitung der weiteren Befehle wird die Grafik zwar wieder überschrieben, aber nach automatischer Aktualisierung passt die Darstellung dann.
Also alles perfekt!
Herzlichen Dank nochmal und einen schönen Sonntag!
Grüße,

Markus
