### ISSUE TITLE
Problems with graphic

### ISSUE THREAD

**Issue by GSHusar** [nischram/E3dcGui#49]
Hi,

I operate a new Raspi 4 (as newbie ;-))

The grapical problems which should be solved with #48 stay, although I followed the instructions step by step.

Kind regards
GSHusar
![IMG_2610](https://user-images.githubusercontent.com/81009677/111863667-4656f580-895d-11eb-9aba-805fda0c791f.jpeg)

**Comment by GSHusar** [comment]
Übrigens wollte ich mich für die tolle Arbeit erst einmal bedanken! Klasse, dass Du das der Allgemeinheit zur Verfügung stellst.

Gruß
GSHusar

**Comment by nischram** [comment]
Hey,
Danke, ich hatte beim erstellen so einige Ideen aus dem Netz geholt, da muss man ja auch was zurückgeben! 

Es wundertet mich, dass die RSCP-Ausgaben zu sehen sind, dass hatte ich sonst noch nicht gesehen.
Wie startest du die Applikation?
1. per Tastatur direkt am Raspberry?
2. per Putty oder andere Netzwerkverbindung zum Raspberry?
3. per crontab nach einen Neustart des Raspberry?

Bei 1. könnte ich mir das Problem vorstellen, ich habe das nicht eingebaut und nicht getestet. Wenn dies der Fall ist mach einfach mit der Erklärung für den [Autostart ](https://github.com/nischram/E3dcGui#autostart-der-applikation-durch-crontab-job)weiter, das Bild sollte dann nach einem reboot korrekt sein.  
Variante 2 wäre die Richtige um die Applikation zu testen. 
Variante 3 ist der Normalbetrieb. 
Bei 2 und 3 sollte eigentlich das Problem aus deinem Foto nicht zu sehen sein. 

Ich hoffe es hilft schon, sonst sehen wir weiter.

Viele Grüße Nico

**Comment by GSHusar** [comment]
Hi Nico,

 

Deine Reaktionszeit ist der Knaller 😉

 

Es war die Nummer 1 – mit autostart hat es direkt geklappt, vielen Dank!

 

Ich habe noch eine zweite Baustelle, vielleicht kannst Du mir auch da auf die Sprünge helfen:

 

Ich möchte die Daten gerne in der HM CCU2 haben, hab das nach Deiner Anleitung getan – die Variablen in der homematic bleiben aber auf null. Ne Idee?

 

Gruß

Gerhard

 

Von: nischram ***@***.***> 
Gesendet: Samstag, 20. März 2021 13:07
An: nischram/E3dcGui ***@***.***>
Cc: GSHusar ***@***.***>; Author ***@***.***>
Betreff: Re: [nischram/E3dcGui] Problems with graphic (#49)

 

Hey,
Danke, ich hatte beim erstellen so einige Ideen aus dem Netz geholt, da muss man ja auch was zurückgeben!

Es wundertet mich, dass die RSCP-Ausgaben zu sehen sind, dass hatte ich sonst noch nicht gesehen.
Wie startest du die Applikation?

1.	per Tastatur direkt am Raspberry?
2.	per Putty oder andere Netzwerkverbindung zum Raspberry?
3.	per crontab nach einen Neustart des Raspberry?

Bei 1. könnte ich mir das Problem vorstellen, ich habe das nicht eingebaut und nicht getestet. Wenn dies der Fall ist mach einfach mit der Erklärung für den Autostart  <https://github.com/nischram/E3dcGui#autostart-der-applikation-durch-crontab-job> weiter, das Bild sollte dann nach einem reboot korrekt sein.
Variante 2 wäre die Richtige um die Applikation zu testen.
Variante 3 ist der Normalbetrieb.
Bei 2 und 3 sollte eigentlich das Problem aus deinem Foto nicht zu sehen sein.

Ich hoffe es hilft schon, sonst sehen wir weiter.

Viele Grüße Nico

**Comment by nischram** [comment]
Hallo Gerhard,

diesen Issue schließe ich, aber deine neue Anfrage bearbeite ich in Issue #50 weiter.

VG Nico
