### ISSUE TITLE
Werte werden nicht in die Homematic übertragen

### ISSUE THREAD

**Issue by nischram** [nischram/E3dcGui#50]
Hi Nico,

Deine Reaktionszeit ist der Knaller 😉

Es war die Nummer 1 – mit autostart hat es direkt geklappt, vielen Dank!

Ich habe noch eine zweite Baustelle, vielleicht kannst Du mir auch da auf die Sprünge helfen:

Ich möchte die Daten gerne in der HM CCU2 haben, hab das nach Deiner Anleitung getan – die Variablen in der homematic bleiben aber auf null. Ne Idee?

Gruß
Gerhard

**Comment by nischram** [comment]
@GSHusar
Hallo Gerhard,
dann bleib ich mal bei der Reaktionszeit ;-)

Oh das mit den Daten in der HM kann verschiedene Gründe haben.

- ISE-ID aus der HM ausgelesen und in die parameter.h übertragen
- In der parameter.h in Zeile 24  die Verwendung auf "1" setzten
- In der parameter.h in Zeile 25 die IP-Adresse der Homematic eingetragen
- In der parameter.h in Zeile 25 die Zeit nicht zu groß wählen, ich empfehle 15 oder 30 Sekunden
- nach den Änderungen in der parameter.h die Applikation neu kompilieren mit `make`
- Applikation oder Raspberry nach jedem make neu starten.
- Homematic und Speicher befinden sich nicht im selben Netzwerk, der Beginn der IP muss gleich sein nur die Endung darf abweichen z.B. 192.168.178.xxx

So auf die schnelle waren das die Ideen und Tipps, auch hier gehts weiter wenn es nicht direkt klappt.

Viele Grüße Nico

**Comment by GSHusar** [comment]
Hallo Nico,

 

auch hier wieder: Antwort 1 weist den Weg…

 

Ich lass Dich erst mal damit in Ruhe, die Frage war zu voreilig – da muss ich noch einmal gründlicher durch Deine Anleitung (lag bei mir am mangelnden Verständnis zu den ISE-IDs, die sind mir das erste Mal untergekommen). Sollte es klemmen, melde ich mich – da muss ich erst mal meine Schularbeiten machen 😉

 

Gruß

Gerhard

 

Von: nischram ***@***.***> 
Gesendet: Samstag, 20. März 2021 16:36
An: nischram/E3dcGui ***@***.***>
Cc: GSHusar ***@***.***>; Mention ***@***.***>
Betreff: Re: [nischram/E3dcGui] Werte werden nicht in die Homematic übertragen (#50)

 

@GSHusar <https://github.com/GSHusar> 
Hallo Gerhard,
dann bleib ich mal bei der Reaktionszeit ;-)

Oh das mit den Daten in der HM kann verschiedene Gründe haben.

*	ISE-ID aus der HM ausgelesen und in die parameter.h übertragen
*	In der parameter.h in Zeile 24 die Verwendung auf "1" setzten
*	In der parameter.h in Zeile 25 die IP-Adresse der Homematic eingetragen
*	In der parameter.h in Zeile 25 die Zeit nicht zu groß wählen, ich empfehle 15 oder 30 Sekunden
*	nach den Änderungen in der parameter.h die Applikation neu kompilieren mit make
*	Applikation oder Raspberry nach jedem make neu starten.
*	Homematic und Speicher befinden sich nicht im selben Netzwerk, der Beginn der IP muss gleich sein nur die Endung darf abweichen z.B. 192.168.178.xxx

So auf die schnelle waren das die Ideen und Tipps, auch hier gehts weiter wenn es nicht direkt klappt.

Viele Grüße Nico

**Comment by GSHusar** [comment]
Hi Nico,

 

es waren die (nicht korrekt eingetragenen) ISE-IDs – ich bin glücklich, es läuft. DANKE!

 

Jetzt muss ich nur noch meinen touch-screen in den Griff bekommen (reagiert nach Einrichten das Autostart auf nichts mehr)…. Dann ist es perfekt und ich kann die homematic programmieren.

 

Gruß

Gerhard

 

 

Von: nischram ***@***.***> 
Gesendet: Samstag, 20. März 2021 16:36
An: nischram/E3dcGui ***@***.***>
Cc: GSHusar ***@***.***>; Mention ***@***.***>
Betreff: Re: [nischram/E3dcGui] Werte werden nicht in die Homematic übertragen (#50)

 

@GSHusar <https://github.com/GSHusar> 
Hallo Gerhard,
dann bleib ich mal bei der Reaktionszeit ;-)

Oh das mit den Daten in der HM kann verschiedene Gründe haben.

*	ISE-ID aus der HM ausgelesen und in die parameter.h übertragen
*	In der parameter.h in Zeile 24 die Verwendung auf "1" setzten
*	In der parameter.h in Zeile 25 die IP-Adresse der Homematic eingetragen
*	In der parameter.h in Zeile 25 die Zeit nicht zu groß wählen, ich empfehle 15 oder 30 Sekunden
*	nach den Änderungen in der parameter.h die Applikation neu kompilieren mit make
*	Applikation oder Raspberry nach jedem make neu starten.
*	Homematic und Speicher befinden sich nicht im selben Netzwerk, der Beginn der IP muss gleich sein nur die Endung darf abweichen z.B. 192.168.178.xxx

So auf die schnelle waren das die Ideen und Tipps, auch hier gehts weiter wenn es nicht direkt klappt.

Viele Grüße Nico

**Comment by nischram** [comment]
Hey,

mich könnte mir vorstellen das auch dieses Problem mit einen Tipp schnell geölt ist. Somit lieber fragen als lange ärgern ☺️!
Da hast ja erwähnt, dass du am Pi ne Tastatur genutzt hast diese wird wie der Touch auch als Eingabegerät erkannt, hat aber oft Vorrang vor dem Touch. Die entsprechende Einstellung hast du in der parameter.h eventuell vorgenommen. 
In Zeile 10 gibt man den Ort vor mit „event0“ oder ähnlichen. Wennn jetzt den Pi ohne Tastatur betreibst wir der Touch unter einer anderen Nummer erkannt. Die Zahl zählt hoch in der Regel passt es wenn du eine Nummer niedriger einträgst. 
Oder du hast den Eintrag gar nicht veränder und du startest mit Tastatur, dann ist jetzt die Tastatur „event0“ und nicht der Touch. Die Software kann bei sucht bei event0 aber den Touch und dann klappt es nicht, dann musst du einfach ohne Tastatur neu starten und es sollte klappen.

So vielleicht klappt es ja wieder auf anhieb. 

Aber wie gesagt lieber fragen als lange suchen 😉!

VG Nico

**Comment by GSHusar** [comment]
Hi Nico,

 

ich habe jetzt erst einmal ausgeschlossen, dass ein hardware-Defekt vorliegt: Wenn ich die boot-Optionen verändere, dass der PI in das PI-eigene GUI einsteigt, erscheint der Mauszeiger, das Gerät ist normal bedienbar.

 

Nach einem boot mit autostart der E3dcGui ist auf dem touch nichts bedienbar, auch wenn der USB-Dongle für die Funktastatur nicht gesteckt ist…

 

Die Zeilen in der parameter.h hatte ich mir angesehen:

 

***@***.***:~/E3dcGui $ ls /dev/input

by-path  event0  event1  mice  mouse0

 

udevadm info --name/dev/input/event0 --attribute-walk

 

ergibt bei mir:

 

***@***.***:~/E3dcGui $ udevadm info --name/dev/input/event0 --attribute-walk

info: unrecognized option '--name/dev/input/event0'

 

Was mache ich falsch? 

 

Gruß

Gerhard

 

Von: nischram ***@***.***> 
Gesendet: Samstag, 20. März 2021 21:26
An: nischram/E3dcGui ***@***.***>
Cc: GSHusar ***@***.***>; Mention ***@***.***>
Betreff: Re: [nischram/E3dcGui] Werte werden nicht in die Homematic übertragen (#50)

 

Hey,

mich könnte mir vorstellen das auch dieses Problem mit einen Tipp schnell geölt ist. Somit lieber fragen als lange ärgern ☺️!
Da hast ja erwähnt, dass du am Pi ne Tastatur genutzt hast diese wird wie der Touch auch als Eingabegerät erkannt, hat aber oft Vorrang vor dem Touch. Die entsprechende Einstellung hast du in der parameter.h eventuell vorgenommen.
In Zeile 10 gibt man den Ort vor mit „event0“ oder ähnlichen. Wennn jetzt den Pi ohne Tastatur betreibst wir der Touch unter einer anderen Nummer erkannt. Die Zahl zählt hoch in der Regel passt es wenn du eine Nummer niedriger einträgst.
Oder du hast den Eintrag gar nicht veränder und du startest mit Tastatur, dann ist jetzt die Tastatur „event0“ und nicht der Touch. Die Software kann bei sucht bei event0 aber den Touch und dann klappt es nicht, dann musst du einfach ohne Tastatur neu starten und es sollte klappen.

So vielleicht klappt es ja wieder auf anhieb.

Aber wie gesagt lieber fragen als lange suchen 😉!

VG Nico

**Comment by nischram** [comment]
Hallo Gerhard,

wenn du direkt am Pi die Bearbeitung machst, bekommst du für Tastatur und Touch die Ausgabe `event0` und `event1`.
Ich Tippe `event1` ist der Touch. `mice` und `mouse0` sind für uns uninteressant die habe ich bei mir auch.

Bei deiner Abfrage fehlt das = hinter name. Oder die Erklärung für das Attribut wird weglassen und nur den "Namen" oder Pfad angeben, der Befehl sieht so aus:
```udevadm info --name=/dev/input/event0```
oder:
```udevadm info --name=/dev/input/event1```
oder ohne Attribut z.B. so:
```udevadm info /dev/input/event0```
Bei mir ohne Tastatur ist `event0` der Touch und ich bekomme folgende Ausgabe:
```
pi@raspberrypi:~ $ udevadm info /dev/input/event0
P: /devices/virtual/input/input0/event0
N: input/event0
E: DEVNAME=/dev/input/event0
E: DEVPATH=/devices/virtual/input/input0/event0
E: ID_INPUT=1
E: ID_INPUT_TOUCHSCREEN=1
E: MAJOR=13
E: MINOR=64
E: SUBSYSTEM=input
E: USEC_INITIALIZED=4658252
```
Da steht was von `ID_INPUT_TOUCHSCREEN` ich Tippe damit erkennt man das es der Touch ist.

Aber denk daran dass nach einem Neustart ohne Tastatur die Reihenfolge von enentX sich ändern kann.
Alternativ musst du versuchen dich per ["PuTTy"(Windows)](https://tutorials-raspberrypi.de/raspberry-pi-ssh-windows-zugriff-putty/) oder per ["Terminal"(Mac)](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjTw-TFsMHvAhXZwQIHHQY4BFc4ChC3AjAAegQIBBAD&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DV6xaVNX44t4&usg=AOvVaw32xtuQpLm4hkiQqc3nAzPl) einloggen.
Dafür musst du am Pi aber zuvor SSH aktivieren.
Wenn du per Ferne eingeloggt bist kannst du ohne die Tastatur am Pi den richtigen Input rausfinden. (und das eventuell bequem vom Sofa oder Schreibtisch aus)

VG Nico

**Comment by GSHusar** [comment]
Hi Nico,

 

ich greife über Remote Desktop (Windows 10) auf den Raspi zu, also tatsächlich vom Sofa aus möglich 😉

 

Nach Eliminierung des Tippfehler in der Abfrage konnte ich nun das Rätsel um event0 / 1 auflösen: ich hatte dem Raspi einen Taster spendiert auf der GPIO als Ein-/Ausschalter. Der hat sich flugs als event0 etabliert. Der Touch war damit event1… in der parameter.h geändert, kompiliert und gefreut 😉 Jetzt läuft alles perfekt und ich kann mich an die Programmierung der CCU2 machen. Das hätte ich ohne Dich nicht  hinbekommen! Darf ich Dir für Deine Mühen eine Tafel „Merci“ anbieten (via PayPal 😉)?

 

Gruß

Gerhard

 

 

 

Von: nischram ***@***.***> 
Gesendet: Sonntag, 21. März 2021 13:30
An: nischram/E3dcGui ***@***.***>
Cc: GSHusar ***@***.***>; Mention ***@***.***>
Betreff: Re: [nischram/E3dcGui] Werte werden nicht in die Homematic übertragen (#50)

 

Hallo Gerhard,

wenn du direkt am Pi die Bearbeitung machst, bekommst du für Tastatur und Touch die Ausgabe event0 und event1.
Ich Tippe event1 ist der Touch. mice und mouse0 sind für uns uninteressant die habe ich bei mir auch.

Bei deiner Abfrage fehlt das = hinter name. Oder die Erklärung für das Attribut wird weglassen und nur den "Namen" oder Pfad angeben, der Befehl sieht so aus:
udevadm info --name=/dev/input/event0
oder:
udevadm info --name=/dev/input/event1
oder ohne Attribut z.B. so:
udevadm info /dev/input/event0
Bei mir ohne Tastatur ist event0 der Touch und ich bekomme folgende Ausgabe:

***@***.***:~ $ udevadm info /dev/input/event0
 
P: /devices/virtual/input/input0/event0
 
N: input/event0
 
E: DEVNAME=/dev/input/event0
 
E: DEVPATH=/devices/virtual/input/input0/event0
 
E: ID_INPUT=1
 
E: ID_INPUT_TOUCHSCREEN=1
 
E: MAJOR=13
 
E: MINOR=64
 
E: SUBSYSTEM=input
 
E: USEC_INITIALIZED=4658252
 

Da steht was von ID_INPUT_TOUCHSCREEN ich Tippe damit erkennt man das es der Touch ist.

Aber denk daran dass nach einem Neustart ohne Tastatur die Reihenfolge von enentX sich ändern kann.
Alternativ musst du versuchen dich per  <https://tutorials-raspberrypi.de/raspberry-pi-ssh-windows-zugriff-putty/> "PuTTy"(Windows) oder per  <https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjTw-TFsMHvAhXZwQIHHQY4BFc4ChC3AjAAegQIBBAD&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DV6xaVNX44t4&usg=AOvVaw32xtuQpLm4hkiQqc3nAzPl> "Terminal"(Mac) einloggen.
Dafür musst du am Pi aber zuvor SSH aktivieren.
Wenn du per Ferne eingeloggt bist kannst du ohne die Tastatur am Pi den richtigen Input rausfinden. (und das eventuell bequem vom Sofa oder Schreibtisch aus)

VG Nico

**Comment by nischram** [comment]
Hi Gerhard,

das freut mich, das es jetzt läuft. Gut zu wissen. dass ein Taster mit der entsprechenden Programmierung sich auch als Input/event  einträgt. Das war mir neu.

Ich freue mich immer wieder wenn mein Display genutzt wird und ich mit der Arbeit eine Freude machen kann. 
Alles Gut, über den Dank alleine freue ich mich schon und so ist eine weiter Geste nicht nötig, aber nett gemeint.

Weiter viel Erfolg beim Programmieren und gerne erneut fragen wenn es was gibt. 
Viele Grüße Nico
