### ISSUE TITLE
No image displayed

### ISSUE THREAD

**Issue by Thomas-sw11** [nischram/E3dcGui#54]
Hallo Nico,
ich bin grade dabei Dein Raspi E3DC Projekt auf meinen Raspi 4 mit 10" Display zu bringen. Dabei sind mir 
2 Sachen aufgefallen:

- zwei Dateien (E3dcCache.txt und E3dcWbCache.txt) sind in der RAMDisk nicht vorhanden: nicht vorhanden, sollen aber beim Programstart kopiert werden:
 		system ("cp /mnt/RAMDisk/**E3dcCache.txt** /mnt/RAMDisk/E3dcGuiData.txt");
		system ("cp /mnt/RAMDisk/**E3dcWbCache.txt** /mnt/RAMDisk/E3dcGuiWbData.txt ");
- es erscheint auf dem Display kein Bild

Hängt das irgendwie zusammen? 

VG Thomas.

**Comment by nischram** [comment]
Hallo Thomas, 

die Dateien werden nicht nur beim Programmstart kopiert sondern permanent in der While-Schleife.
Das benötige ich weil verschiede Programme auf die Daten zugreifen und wenn die an einer Datei arbeiten würden crashen die Programme wenn die sich an der gleichen stelle Treffen. (Kann man vielleicht schöner lösen aber die Lösung funktioniert) 
Wenn die Programme gerade gestartet haben kann es zum Teil noch Fehlermeldungen geben bis alle Teile gestartet haben. 

Auch wenn ich jetzt sage, dass ich zu deinem Problem kein Zusammenhang sehe, merke ich das hier wohl noch Verbesserungsbedarf besteht, aber das gehe ich wann anders an.

Jetzt zu deinem Problem: Grundsätzlich weiß ich nicht ob es mit einem 10" Diasplay funktioniert. Ich habe alles für das 7" Display ausgelegt. Es muss zumindest unbedingt die Auflösung auf 800x480 eingestellt werden.
Bekommst du denn die Raspberry Ausgaben auf das Display oder bleibt es Grundsätzlich dunkel?

Viele Grüße Nico

**Comment by Thomas-sw11** [comment]
Hallo Nico,

 
danke für die schnelle Antwort. 

Ich hatte den Raspberry in den Desktop starten lassen anstatt in die CLI und gedacht, das das Image als Fenster da drüber gelegt wird.

Nachdem ich den Desktop ausgeschaltet habe, wird das Image angezeigt, aber nur als 800x600 in der linken oberen Ecke.

Ich glaube, jetzt komme ich erst mal weiter.

 
Vielen Dank und schöne Grüße

 
Thomas. 

 
 
 
Von: nischram ***@***.***> 
Gesendet: Freitag, 9. April 2021 20:24
An: nischram/E3dcGui ***@***.***>
Cc: Thomas Schumann ***@***.***>; Author ***@***.***>
Betreff: Re: [nischram/E3dcGui] No image displayed (#54)

 
Hallo Thomas,

die Dateien werden nicht nur beim Programmstart kopiert sondern permanent in der While-Schleife.
Das benötige ich weil verschiede Programme auf die Daten zugreifen und wenn die an einer Datei arbeiten würden crashen die Programme wenn die sich an der gleichen stelle Treffen. (Kann man vielleicht schöner lösen aber die Lösung funktioniert)
Wenn die Programme gerade gestartet haben kann es zum Teil noch Fehlermeldungen geben bis alle Teile gestartet haben.

Auch wenn ich jetzt sage, dass ich zu deinem Problem kein Zusammenhang sehe, merke ich das hier wohl noch Verbesserungsbedarf besteht, aber das gehe ich wann anders an.

Jetzt zu deinem Problem: Grundsätzlich weiß ich nicht ob es mit einem 10" Diasplay funktioniert. Ich habe alles für das 7" Display ausgelegt. Es muss zumindest unbedingt die Auflösung auf 800x480 eingestellt werden.
Bekommst du denn die Raspberry Ausgaben auf das Display oder bleibt es Grundsätzlich dunkel?

Viele Grüße Nico

**Comment by nischram** [comment]
Hallo Thomas,

hast du es hinbekommen oder benötigst du noch Hilfe?

VG Nico

**Comment by Thomas-sw11** [comment]
Hallo Nico,

 
ja ich habe es hinbekommen. Danke noch mal für die Rückfrage. Es lag an der Auflösung. Mein 10“ Display hat ja 1280x800.

Letztendlich habe ich aber das UI neu mit gebaut (mit Glade und GTK). Die Daten vom E3DC hole ich per Modbus/TPC ab. 

Auch meine selbstgebaute Ladestation (Laderegler: Phoenix/Contact ) und meine Wärmepumpe (Dimplex) steuere ich über Modbus/TCP.

Nur für den Heizstab verwende ich einen GPIO und ein Relais auf dem Raspi.

 
So schaut‘s jetzt aus.

 

 
Viele Grüße

 
Thomas.

 
Von: nischram ***@***.***> 
Gesendet: Sonntag, 18. April 2021 18:04
An: nischram/E3dcGui ***@***.***>
Cc: Thomas Schumann ***@***.***>; Author ***@***.***>
Betreff: Re: [nischram/E3dcGui] No image displayed (#54)

 
Hallo Thomas,

hast du es hinbekommen oder benötigst du noch Hilfe?

VG Nico

**Comment by nischram** [comment]
Hey, 

super alles klar dann schließe ich den Issue.

Viele Grüße Nico
