### ISSUE TITLE
Befehle von HM zur Wallbox senden

### ISSUE THREAD

**Issue by nischram** [nischram/E3dcGui#56]
**Frage aus dem Homematic-Forum von Johre:** [Anbindung an Stromspeicher E3DC](https://homematic-forum.de/forum/viewtopic.php?f=19&t=30095&e=1&view=unread#p660376)

Ist es möglich, auch umgekehrt Daten (Befehle) aus der Homematic an den Raspi zu schicken und über Deine Anwendung die Wallbox zu steuern.
Über das Display des Raspi geht das ja. 
Ich würde gerne folgende Einstellungen aus der HM steuern: 
max. Ladestrom, Sonnenmodus ein/aus (nur Überschussladung oder auch aus dem Netz), Stopp und Start des Ladens.

**Comment by nischram** [comment]
Ich denke das ich mir da was einfallen lassen könnte. Ich würde dann eine bestimmte Variable alle X Sekunden abfragen und als Träger nutzen, um dann bei bedarf mehrere Variablen abzufragen um diese Werte zu senden. Was ich aktuell nicht hinbekommen habe ist das manuelle stoppen und starten.

**Comment by nischram** [comment]
Mit V1.89 integriert. 
Anleitung im Wiki: [Wallbox in die Homematic einbinden](https://github.com/nischram/E3dcGui/wiki/Wallbox-in-die-Homematic-einbinden)

**Comment by nischram** [comment]
Ich habe doch noch eine Möglichkeit gefunden die Ladung zu stoppen.
Ist jetzt Im Wallbox-Menü rechts oben zu finden und aktiv wenn die Ladung läuft.
![IMG_4416](https://user-images.githubusercontent.com/19279623/120035963-afaf5080-bfff-11eb-8d0a-2ca8734f514b.jpg)

**Comment by bs0001** [comment]
Hallo Nico,
ich würde auch gerne ohne Display (sondern über die Homematic direkt) die Notstromreserve anpassen.

So wie ich das sehe, geht das aktuell nur mit dem Display, oder?

Ich habe mal zusammengeschrieben, welche Steps ich sehe, um das zu realisieren:

Notstromreserve setzen ohne Display

1. Systemvariablen in Homematic anlegen
S10_SEND_NOW als Logikwert, analog S10_WALLBOX_SEND_NOW
S10_SEND_NOW_ACTION als Zeichenkette, dann kann man zukünftig beliebige Actions eintragen und in Deinen Programmen drauf reagieren

2. parameter.h ergänzen
- Tags definieren:
#define ISE_HM_SEND_NOW                      0            // ISE_ID Anforderung fÃ¼rs senden
#define ISE_HM_SEND_NOW_ACTION               0            // ISE_ID Anforderung fÃ¼rs definierte Aktion
#define TAG_EMS_ISE_EMERGENCY_POWER_SIZE     0			  // ISE_ID Size of emergency power in Wh
#define ISE_HM_SEND_EMERGENCY_POWER_SIZE     0			  // ISE_ID Size of emergency power in Wh

3. actionCheckHM.c erstellen
Erstellung "actionCheckHM.c" durch Kopie der Datei "wbCheckHM.c"
- Inhaltliche Anpassung der Datei durch Abfrage der beiden o.s. ISE-IDs (ISE_HM_SEND_NOW & ISE_HM_SEND_NOW_ACTION).
- Codingauszüge dann in etwa so:
	read_HM(ISE_HM_SEND_EMERGENCY_POWER_SIZE, 2, HmEpSize);
	snprintf (OUT, (size_t)128, "/home/pi/E3dcGui/Rscp/RscpSet -ep", HmEpSize);
	
4. make Rscp/actionCheckHM

5. Homematic-Programme entsprechend erstellen, in dem bei Änderung der Emergency-Size und Drücken eines Speichern-Buttons, die beiden Variablen für ISE_HM_SEND_NOW_ACTION und ISE_HM_SEND_NOW gefüllt werden.

Schau bitte mal drüber, ob ich hier was vergessen habe oder ob es eine einfachere Möglichkeit gibt.


Wie in [Issue 53](https://github.com/nischram/E3dcGui/issues/53) geschrieben würde ich auch gerne die maximale Ladeleistung (bei gutem Wetter darf es gerne weniger sein, schont den Akku) sowie Sperrzeiten übermitteln können.
Vielleicht hast Du ja bereits was davon in Planung. Ansonsten müssten entsprechende Programme erweitert werden. Muss ich mir aber erst noch genauer ansehen.

Was bislang noch nicht ging war der Tagesertrag für MPP1 und MPP2 zu ermitteln. Lt. E3DC wurden diese Parameter noch nicht auslesbar zur Verfügung gestellt. Vielleicht ja mittlerweile mit dem aktuellen Software-Stand (P10_2021_044).

Besten Dank und viele Grüße
Bernd
