### ISSUE TITLE
Neue Funktion zum beenden des Programms einfügen

### ISSUE THREAD

**Issue by fro5fr** [nischram/E3dcGui#59]
Hallo Nico,

ich fände eine Funktion auf der Einstellungsseite gut, die quasi das Programm beendet damit man in die Kommando Zeile kommt.
Einfach ausgedrückt per Button ein "./stop"  ausführen.

Danke und Gruß,
Eric

**Comment by nischram** [comment]
Hey Eric,

oh, da hatte ich dich wohl falsch verstanden. 
Das ist noch einfacher und sollte kein Problem darstellen. Ich werde es beim nächsten Update einbringen.

VG Nico

**Comment by nischram** [comment]
Hallo Eric,

habe die Stop-Funktion jetzt in Update V1.91 mit hochgeladen.

VG Nico

**Comment by fro5fr** [comment]
Danke.
Der Button schaltet des Programm zwar aus, aber leider sehe ich kein Eingabeprompt.
per SSH ist der Pi aber noch erreichbar.
Eine Idee an was das liegen könnte?

Danke und Gruß,
Eric

**Comment by nischram** [comment]
Hey,

das ist etwas Problematisch. 
[Pi-Funktionen-deaktivieren](https://github.com/nischram/E3dcGui/wiki/Pi-Funktionen-deaktivieren)
In diesem Teil meiner Anleitung wird der Cursor abgestellt und so blinkt da nix mehr. Das Prompt kommt eventuell wenn man auf der Tastatur am Pi die Enter taste drückt. 

Was genau möchtest du denn mit dem Button erreichen?
Wenn du zum Testen damit die Software immer wieder stoppen willst, dann funktioniert das trotzdem.

VG Nico

**Comment by fro5fr** [comment]
Hallo Nico,
danke - das war für Pi neuling alles was ich gebraucht habe.
Ich habe lediglich nicht bemerkt das der Cursor nicht sichtbar ist, aber mit Enter kommt man in die Shell... 
Somit alles perfekt.
Danke.
Gruß,
Eric
