### ISSUE TITLE
Anzeige der Tracker Spannung und Stromstärke identisch

### ISSUE THREAD

**Issue by fro5fr** [nischram/E3dcGui#60]
Hallo Nico,
bei der Anzeige der zwei Tracker sind die Spannung und Stromstärke immer identisch.
Die Leistung allerdings unterschiedlich - was auch korrekt ist.

Gibt E3DC hier nur einen Wert raus oder wird hier vielleicht eine variable verrutscht :-)

Danke vor allem für die vielen nützlichen und schnellen updates und Gruß,
Eric

**Comment by nischram** [comment]
Hallo Eric,

gut aufgepasst, ich habe ziemlich gleiche Springs so war mir der Fehler nicht aufgefallen.
Jetzt bei der Anpassung auf größere Zahlen habe ich dort beim kopieren vergessen die Tracker-Nr zu ändern.
Es ist eine kleine Änderung in der GuiMain.c habe es hochgeladen. Wenn du es ohne Update ändern Wills hier ein Screenshot:
<img width="759" alt="Bildschirmfoto 2021-05-30 um 13 28 55" src="https://user-images.githubusercontent.com/19279623/120102488-91566b80-c14b-11eb-949e-e629021c5e05.png">

Viele Grüße Nico

**Comment by fro5fr** [comment]
Hallo Nico,
super - danke   funktioniert jetzt wieder :-)
Gruß,
Eric
