### ISSUE TITLE
Nach Umstieg auf die neue Version habe ich keine History Anzeige

### ISSUE THREAD

**Issue by hhofer71** [nischram/E3dcGui#62]
Hallo, die Einstellung in parameter.h für die History steht auf "1" und auf "900" wie angegeben. Wenn ich auf History Tippe kommt die Anzeige "Today 31.12. 23:59" und alle Werte sind auf "0". Was habe ich übersehen? Viele Grüße, hhofer

**Comment by nischram** [comment]
Hey,
die History Daten frage ich alle "x" Sekunden (bei dir dann alle 900 Sekunden) ab. Für die Abfrage wird das Program S10History verwendet was sich eigentlich beim make auch einrichten sollte.
Du kannst die Abfrage mal einzeln testen, mit diesem Befehl:
`/home/pi/E3dcGui/S10history/S10history -T`
Die Ausgabe sollte etwa so aussehen:
<img width="682" alt="Bildschirmfoto 2021-07-29 um 20 10 28" src="https://user-images.githubusercontent.com/19279623/127544568-c8d4a5b8-2336-4e3e-ba8e-16e514ba0695.png">

Wenn das nicht klappt solltest du testen ob der make Befehl für S10History klappt (durchläuft). Befehl:
`make S10history/S10history`

Vielleicht passt beim Pi auch irgendwas mit der Uhrzeit nicht, die Zeit kannst du mit `date` kontrollieren.

Viele Grüße Nico

**Comment by hhofer71** [comment]
Danke für Deine schnelle Antwort,
habe die Abfrage einzeln getestet - das Ergebnis siehst du ganz unten.
Schon beim compielieren kommen vielen Fehlermeldungen wie "yesterday was not decleared in this scope" und so weiter.

Eine Kopie davon:

S10history/../define.h:184: note: it was later defined here
 #define yesterday                   2    //!!

In file included from S10history/RscpReader.cpp:26:
S10history/../Rscp/RWData.h:274:43: error: ‘today_path’ was not declared in this scope
    snprintf (filePath, (size_t)128, "%s", today_path);
                                           ^~~~~~~~~~
S10history/../Rscp/RWData.h:274:43: note: the macro ‘today_path’ had not yet been defined
In file included from S10history/../parameter.h:4,
                 from S10history/RscpReader.cpp:27:
S10history/../define.h:185: note: it was later defined here
 #define today_path                  "/mnt/RAMDisk/today.txt"         //!!

In file included from S10history/RscpReader.cpp:26:
S10history/../Rscp/RWData.h:277:43: error: ‘yesterday_path’ was not declared in this scope
    snprintf (filePath, (size_t)128, "%s", yesterday_path);
                                           ^~~~~~~~~~~~~~
S10history/../Rscp/RWData.h:277:43: note: the macro ‘yesterday_path’ had not yet been defined
In file included from S10history/../parameter.h:4,
                 from S10history/RscpReader.cpp:27:
S10history/../define.h:186: note: it was later defined here
 #define yesterday_path              "/mnt/RAMDisk/yesterday.txt"     //!!

In file included from S10history/RscpReader.cpp:26:
S10history/../Rscp/RWData.h:279:45: error: ‘dataMax’ was not declared in this scope
     writeData(filePath, Position, NewValue, dataMax);
                                             ^~~~~~~
S10history/../Rscp/RWData.h:279:45: note: the macro ‘dataMax’ had not yet been defined
In file included from S10history/../parameter.h:4,
                 from S10history/RscpReader.cpp:27:
S10history/../define.h:180: note: it was later defined here
 #define dataMax                     7    //!!

In file included from S10history/RscpReader.cpp:26:
S10history/../Rscp/RWData.h: In function ‘int writeHistoryTime(int, int, int, int)’:
S10history/../Rscp/RWData.h:287:19: error: ‘today’ was not declared in this scope
   if(writedata == today)
                   ^~~~~
S10history/../Rscp/RWData.h:287:19: note: the macro ‘today’ had not yet been defined
In file included from S10history/../parameter.h:4,
                 from S10history/RscpReader.cpp:27:
S10history/../define.h:183: note: it was later defined here
 #define today                       1    //!!

In file included from S10history/RscpReader.cpp:26:
S10history/../Rscp/RWData.h:289:24: error: ‘yesterday’ was not declared in this scope
   else if(writedata == yesterday)
                        ^~~~~~~~~
S10history/../Rscp/RWData.h:289:24: note: the macro ‘yesterday’ had not yet been defined
In file included from S10history/../parameter.h:4,
                 from S10history/RscpReader.cpp:27:
S10history/../define.h:184: note: it was later defined here
 #define yesterday                   2    //!!

In file included from S10history/RscpReader.cpp:26:
S10history/../Rscp/RWData.h: In function ‘int writeHistory(int, int, int)’:
S10history/../Rscp/RWData.h:283:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Makefile:43: S10history/S10history] Fehler 1

**pi@pi4:~/E3dcGui $ /home/pi/E3dcGui/S10history/S10history -T
-bash: /home/pi/E3dcGui/S10history/S10history: Datei oder Verzeichnis nicht gefu                                                                                                                                                             nden**

Uhrzeit habe ich geprüft - die stimmt.

Viele Grüße Helmut

**Comment by hhofer71** [comment]
Hallo Nico, ich habe es auf einem zweiten Raspi getestet, bei dem kommt der selbe Fehler. 
Vielleicht liegt es daran das ich die Datei parameter.h und parameterHM.h von meiner alten Installation kopiert und in die neue eingefügt habe - ist das möglich?

**Comment by hhofer71** [comment]
![image](https://user-images.githubusercontent.com/88159311/127559129-d8e29079-5bcc-4edf-adf9-69f1910be9ee.png)

Jetzt weis ich auch wie man Bilder hier einfügt 😁!

**Comment by nischram** [comment]
Hallo Helmut,

ich habe einen Fehler in meiner Software gefunden. Ich hatte in dem Update V2.00 eine Datei vergessen hochzuladen. So war diese noch auf dem alten Stand und der Fehler be dir ist entstanden. Dank deiner Bilder und Kopien der Fehlermeldungen konnte ich den unterschied zwischen den Dateien bei mir und dem hier im Github finden. Da die Datei bei mir richtig war, ist der Fehler bei mir nicht aufgefallen. 
Mit einem `git pull` kannst du das Update von gerade eben laden und der Befehl `make S10history/S10history` sollte durchlaufen.

Sorry für die Umstände und viele Grüße Nico

**Comment by hhofer71** [comment]
Super, die manuelle Abfrage funktioniert schon, beim compielieren auch keine Fehlermeldungen mehr. Jetzt hat er auch schon die Daten von gestern geladen - alles funktioniert jetzt super! 
Vielen Dank für deine Mühe und die tollen Projekte - das Modbus Display baue ich nächste Woche nach, so etwas fehlte mir noch!
Übrigens, die E3dcGui benutze ich um mit den Aktoren mein E-Auto mit Überschuss zu laden. Perfekt!
Nochmals vielen Dank!
Grüße, Helmut

**Comment by nischram** [comment]
Das hört sich doch sehr gut an. Danke fürs Feedback.
Ich bin gerade dabei, in der nähe der Wallbox ein weiteres Display hin zu bauen (eventuell auch nur das kleine) um die Wallbox entsprechend zu steuern, direkt wenn ich das Auto anstecke und nicht erst im Haus (eine Stunde später wenn ich es mal wieder vergessen habe und der Akku schon wieder leer gezogen wird 😉).
Gruß Nico
