### ISSUE TITLE
Langzeitanzeige Fehler

### ISSUE THREAD

**Issue by hhofer71** [nischram/E3dcGui#63]
Hallo Nico,
heute habe ich einen weiteren Fehler bei mir entdeckt. Wenn man auf die Langzeitanzeige abruft kommt folgendes Bild:

![Langzeitanzeige Fehler](https://user-images.githubusercontent.com/88159311/127751260-604c4ee6-f142-4e14-9493-5a99a9e9f2d6.jpg)
Dann reagiert der Touch nur noch zum ausschalten des Bildschirmes. Nach einige Zeit springt der der Bildschirm wieder auf die Standard Anzeige zurück und in der Watchdog.csv ist folgender Eintrag dazu:

**31.07.2021;22:11:42;1627762302;1627761942;22;GuiMain-kill**

Wenn ich die "S10History" ausschalte tritt dieser Fehler nicht auf. Mir ist die History aber wichtig, die Langzeit Anzeige ist entbehrlich.
Kann man die Funktion Langzeitanzeige auch ganz ausschalten? Da ich einen 32kWh Akku habe ist die Anzeige bei mir eh nicht sonderlich nützlich. 
Ich hoffe ich nerve nicht zu sehr 🤔!
Schönes Wochenende und viele Grüße,
Helmut

**Comment by nischram** [comment]
Hallo Helmut,

die Problematik ist mir bekannt. 
Erstmal zur Info: Die Langzeitwerte haben nicht mit den HistoryValues zu tun, dir Langzeitwerte Speicher ich mit der RscpMain ab. 
Beim Aufrufen des Screens werden die gespeicherten Werte aufgerufen und gemäß der Einstellung in der parameter.h ungerechnet damit sie in den Screen passen. Sollte nun die Einstellung nicht korrekt sein und der Wert der Angezeigt werden soll, von der höhe nicht ins Bild passen stürzt die Software ab. 
Der Absturz passt zum Eintrag vom Watchdog. 
Das Abstürzen kannst du umgehen in dem du in der parameter.h die Einstellung passend wählst. Es sind diese Werte:
```
//Einstellungen Langzeitanzeige (15 Minuten Mittelwerte in duchrlaufender 24 Stundenanzeige)
#define PowerMax                    5400                    // maximal zu erwartende Leistung als 15Min Mittelwert für Solarproduktion oder Hausverbrauch
#define BatMax                      3000                    // maximale Batterieleistung
#define skalaLine                   1000                    // Einteilung der Scala
```
So muss du die Werte für PowerMax und BatMax anpassen, wahrscheinlich größer einstellen. Da bei dir noch ein kleiner Teil der grünen Linie zu sehen ist würde ich mindestes auf BatMax tippen denn die neueren Speicher von E3DC können ja zum Teil mehr Ladeleistung als meine 3000Watt.

Die kWh vom Akku haben auf den Screen keine Auswirkung da der Wert in SOC (Füllstand) angegeben wird und nicht in kWh.

Grundsätzlich muss ich aber wohl mal die Funktion so anpassen, dass die Software nicht abstürzt. So dass dann ggf. die Linie oben einfach gedeckelt wird. (Würde mi auch helfen immer wenn die Sauna gelaufen hat darf ich den Langzeitscreen nicht aufrufen dann stürzt es bei mir auch ab, wegen der 5400 bei PowerMax die sich auch auf den Hausverbruch auswirkt.

Viele Grüße Nico

**Comment by hhofer71** [comment]
Hallo Nico,

 

jetzt ist alles klar, meine Batterie kann gut 10kW laden/entladen. Und manchmal funktioniert es ja, wenn die Leistung geringer ist – alles klar!

 

Vielen Dank für die Erklärung und schönen Abend noch,

 

Helmut

 

 

Von: nischram ***@***.***> 
Gesendet: Sonntag, 1. August 2021 18:49
An: nischram/E3dcGui ***@***.***>
Cc: hhofer71 ***@***.***>; Author ***@***.***>
Betreff: Re: [nischram/E3dcGui] Langzeitanzeige Fehler (#63)

 

Hallo Helmut,

die Problematik ist mir bekannt.
Erstmal zur Info: Die Langzeitwerte haben nicht mit den HistoryValues zu tun, dir Langzeitwerte Speicher ich mit der RscpMain ab.
Beim Aufrufen des Screens werden die gespeicherten Werte aufgerufen und gemäß der Einstellung in der parameter.h ungerechnet damit sie in den Screen passen. Sollte nun die Einstellung nicht korrekt sein und der Wert der Angezeigt werden soll, von der höhe nicht ins Bild passen stürzt die Software ab.
Der Absturz passt zum Eintrag vom Watchdog.
Das Abstürzen kannst du umgehen in dem du in der parameter.h die Einstellung passend wählst. Es sind diese Werte:

//Einstellungen Langzeitanzeige (15 Minuten Mittelwerte in duchrlaufender 24 Stundenanzeige)
 
#define PowerMax                    5400                    // maximal zu erwartende Leistung als 15Min Mittelwert für Solarproduktion oder Hausverbrauch
 
#define BatMax                      3000                    // maximale Batterieleistung
 
#define skalaLine                   1000                    // Einteilung der Scala
 

So muss du die Werte für PowerMax und BatMax anpassen, wahrscheinlich größer einstellen. Da bei dir noch ein kleiner Teil der grünen Linie zu sehen ist würde ich mindestes auf BatMax tippen denn die neueren Speicher von E3DC können ja zum Teil mehr Ladeleistung als meine 3000Watt.

Die kWh vom Akku haben auf den Screen keine Auswirkung da der Wert in SOC (Füllstand) angegeben wird und nicht in kWh.

Grundsätzlich muss ich aber wohl mal die Funktion so anpassen, dass die Software nicht abstürzt. So dass dann ggf. die Linie oben einfach gedeckelt wird. (Würde mi auch helfen immer wenn die Sauna gelaufen hat darf ich den Langzeitscreen nicht aufrufen dann stürzt es bei mir auch ab, wegen der 5400 bei PowerMax die sich auch auf den Hausverbruch auswirkt.

Viele Grüße Nico
