### ISSUE TITLE
DC Power je Tag je Tracker

### ISSUE THREAD

**Issue by bs0001** [nischram/E3dcGui#68]
Hallo Nico,

gibt es eine Möglichkeit die DC-Power je Tag auszulesen?
Im E3DC-Portal wird es ja auch angezeigt.
Ich hätte gerne die Tageserträge für Tracker 1 und 2.

In der Datei "RscpReader.cpp" wird dieser für die Gesamte PV-Leistung ja mit diesem Tag ausgelesen: TAG_DB_DC_POWER

Für Tracker 1 und 2 habe ich nichts gefunden. Das Portal muss es ja aber auch irgendwie ermitteln.

Vielleicht hast Du eine Idee.

Viele Grüße
Bernd

**Comment by nischram** [comment]
Hallo Bernd,

ich musste jetzt einen Moment überlegen was du meinst denn Power habe ich doch drin, aber du meinst sicher Energie. Das habe ich auch schon vergeblich gesucht. Ich habe nichts gefunden. Wie die Daten im Portal generiert werden und ob man es doch hinbekommt weiß nicht.
Aber vielleicht gibt es ja mal eine neue RSCP-TAG Liste und es ist doch möglich.

Gruß Nico
PS: hoffe es ist OK, ich schließe den Issue  erstmal denn das liegt ja nicht in meiner Hand...

**Comment by bs0001** [comment]
Hi Nico,

ja, das ist der Tageswert.
Ich hatte vor ein paar Tagen mit der Hotline telefoniert. Der Link auf die aktuellste Service-Doku ist im E3DC-Portal unter Downloads zu finden, dort unter der RSCP-Beispielapplikation (Anleitung für Entwickler) und darin auf Seite 7.
Wahnsinnig gut versteckt. Diese ist aber immer noch aus 2016.
Hab versucht zu debuggen im Browser, bin aber leider nicht weiter gekommen. Ja, ich meinte den Tagesertragswert der Solarproduktion für Tracker 1 und 2. Die Gesamte Solarproduktion bekommen wir ja jetzt schon. Die Tracker wären halt interessant.

Hatte es schon vor geraumer Zeit als Verbesserungsvorschlag für die RSCP-Doku beim E3DC-Support eingekippt und beim jetzigen Telefonat nochmal mitgegeben, dass es schön wäre, wenn bald ein Update käme, was so neues möglich ist.
Hatte auch denen ihr Excel komplett weiterentwickelt und ihnen angeboten, dass sie meins nehmen dürfen.

Schauen wir mal, ob vielleicht bald mal was kommt. Die Hoffnung stirbt zuletzt.
So lange gehe ich am Monatsanfang hin, suche mir die besten Tage des Vormonats raus für Tracker 1 und 2 und trage es manuell in die Homematic-Variablen ein. Automatisch wäre natürlich schöner. Das mache ich bei der gesamten Solarproduktion so. Jeden Tag nachts checke ich, ob ein Bestwert erreicht wurde. Falls ja, wird er in die jeweilige Lifetime Monatsvariable samt Datum geschrieben.

Gerne zeige ich Dir mal meine Implementierung. Schreib mich dann aber privat an.

Viele Grüße
Bernd
