### ISSUE TITLE
Batterie-Limits am E3DC einstellen

### ISSUE THREAD

**Issue by holgerkch** [nischram/E3dcGui#80]
Ich habe nach ein paar Anlaufschwierigkeiten (als totaler github und Linux Anfänger) das E3DC Gui erfolgreich installiert.
Super Ding, vielen Dank dafür !

Im Menue Batterie Limits habe ich zwei Fragen
1. Ich schaffe es nicht den Schalter auf Automatik zu stellen, er bleibt immer auf manuell. Geht das irgendwie und was bedeutet "Automatik" dann genau ?
2. Wo kann man diese Batterie Limits am Bildschirm des E3DC selbst einstellen ? Ich habe das nirgendwo in den Menues finden können

Hintergrund meiner Fragen ist, dass ich wohl unabsichtlich irgendwie das Charge Limit auf 2000 gestellt hatte und mich gewundert habe, warum mein E3DC so "merkwürdig" lädt, nämlich einen grossen Teil ins Netz statt in die Batterie.

Grüsse aus Bern
Holger

**Comment by holgerkch** [comment]
Hallo Nico,
ja genau dort war es zu finden. Hatte wohl Tomaten auf den Augen ;-)
Sowohl im Portal wie auch auf dem Display, und dort habe ich es jetzt mal wieder auf Auto zurückgestellt

Ich hab das E3DC (ein S10 PRO Compact) noch nicht so lange und wohl irgendwie noch nicht alles ganz im Griff...
Ist aber schon was feines, und jetzt muss ich dank deiner App auch nicht dauernd in den Keller um die "Livedaten" zu sehen

Gruss
Holger

**Comment by nischram** [comment]
Ich habe den Fehler mit dem Schalter nochmal versucht nachzustellen, aber bei mir klappt aktuell alles. Ich schließe den Issue erstmal wenn jemand den Fehler hat kann der Issue wieder geöffnet werden.
