### ISSUE TITLE
[Question/Frage] Anzeige des Displays per interne Netzwerk IP

### ISSUE THREAD

**Issue by radasbona** [nischram/E3dcGui#86]
Hallo,
eine Homematic besitze ich nicht. Dafür ein altes Android 4 Tablett das nur noch unbenutzt herumliegt.

Ich hab mir gedacht man könnte dieses als zusätzliches Display für unser S10 verwenden. Ein Pi läuft sowieso immer für unsere Nextcloud. (incl. Apache Server)
Ginge es per interne IP Adresse auf die Oberfläche zuzugreifen?

**Comment by nischram** [comment]
Hey,

nein so eine Funktion habe ich nicht eingebaut. Hauptaugenmerk meiner Software ist es entweder eine Homematic mit Daten zu versorgen und / oder ein 7" Display für den Raspberry zu nutzen. Externe oder andere Displays kann man bei meiner Software nicht anbinden. 

Viele Grüße Nico

**Comment by radasbona** [comment]
Ok. 
Vielleicht was für die Zukunft. Würde die Zielgruppe für die Software bestimmt erweitern.

Danke für die schnelle Antwort.
