### ISSUE TITLE
E3dcGui auf Synology NAS

### ISSUE THREAD

**Issue by bs0001** [nischram/E3dcGui#88]
Hallo Nico,

lässt sich das Projekt auch auf einer Synology NAS mit x64 Kernel (DS923+) betreiben, z.B. in einer VM oder in einem Docker Container?
Falls ja, was wäre empfehlenswert zu nehmen?

Viele Grüße 
Bernd

**Comment by nischram** [comment]
Hallo Bernd,
da muss ich jetzt ehrlich mitteilen das ich dir dazu keine richtige Antwort geben kann.
Wenn du da Linux laufen lassen kannst, könnte es sein.
Sorry, dass ich das nicht näher eingrenzen kann.

Viele Grüße Nico

**Comment by bs0001** [comment]
Hi Nico, 
Danke für die Rückmeldung!
Ich hab als VM auf der Synology ein Linux Mint 21.2 am Laufen. Ich werde mal versuchen, dort Dein Projekt einzurichten und von dort dann in die Homematic VM (RaspberryMatic, aktuell ist noch alles auf dem Raspi) die Daten zu schreiben. 
VG
Bernd
